### ISSUE TITLE
Firmware Update Module (Whitebeet User Manual r2.2) 

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#1]
I have been reading through the new revision of the Whitebeet User Manual (r2.2) and have two questions about the Firmware Update Module and associated data types.

1. What data type s `PktNum` supposed to be?
    * uint8 as published in the in the parameter definition?
    * uint32 as it appears to be in the example?
2. What data type is `Data` supposed to be?
    * a byte array with a _maximum length_ of 2000? 
    * Or is this a _fixed length_ array like a 2 kB page of memory? 
    * Or is the array defined by the payload size minus the number of bytes used to represent `PktNum` ?(i.e. `PayloadSize-4` assuming that `PktNum` is uint32_t) This is what the example seems to indicate.  
***
![fwu](https://user-images.githubusercontent.com/29818706/124936764-7093f800-dfcc-11eb-822a-79e0bd36b5de.png)  
***
Thanks for your time

**Comment by jpo-stx** [comment]
Hi @zacharyalutz,

1. The datatype of PktNum should be of type uint32.
2. Data is a bytearray of variable size of up to 2000 bytes. It’s size is determined by payload size minus size of PktNum.

BR
Jan
