### ISSUE TITLE
sub id in the code are different with the one in the manual

### ISSUE THREAD

**Issue by zhanglongqi** [Sevenstax/FreeV2G#106]
Your Setup
Platform: EVSE
Firmware Version: i.e. V01_01_07
Host Controller Interface: Ethernet
Host: FreeV2G (EVSE_v1.1.7_1) 
git commit hash: 12eb962

**Describe the bug**
as the title says

![image](https://user-images.githubusercontent.com/956693/201830345-99216927-ec74-45e1-8187-795be76f0529.png)
![image](https://user-images.githubusercontent.com/956693/201830380-b7606cc2-e269-470a-988e-d3c1e23e80eb.png)

**Comment by jpo-stx** [comment]
@zhanglongqi ,
I think you do not use the correct manual version for your WB firmware version. If you use the WB firmware version 1.1.7 please use the manual from the tag https://github.com/Sevenstax/FreeV2G/tree/EVSE_v1.1.7_1 which is manual version 2.11.2.

See 19.8.4 Charge Parameter Discovery chapter in the manual:

![grafik](https://user-images.githubusercontent.com/84077922/201884656-f3213505-cbc2-449a-996b-4a2a948d2030.png)

**Comment by zhanglongqi** [comment]
Thanks, I can find the manual change log at the end of the manual. Is there a change log for the firmware? Who should I approach if I want to update the firmware?

**Comment by jpo-stx** [comment]
Please read the introduction chapter https://github.com/Sevenstax/FreeV2G#introduction

You should be able to donwload the latest firmware from Codico https://downloads.codico.com/misc/plc/
