### ISSUE TITLE
Control Pilot Service: unexpected state change 0-->6-->0

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#11]
When running ISO15118 firmware as EVSE on a whitebeet carrier board, I observe seemingly random fluctuations in CP state. I made note of this with an engineer from CODICO several months ago. Since then, as a result of our communications, there was a new firmware release to address this issue. However, I am still observing the same behavior. Below are some facts regarding my setup followed by questions/remarks.

### Facts

1. Current firmware version: v01.01.02
2. No connector attached to Whitebeet
3. Commanding State A: +12V / 100% duty cycle.
4. Measured +12.15V with respect to PE.
5. State toggles randomly between 0 and 6 (respectively: "State A" and "state unknown" according to documentation)
6. UART debug interface reports an error similar to the following just before state flips to "6"
`[ 7030.898] [ERROR ] V2GCPS:   UNKNOWN - 4648`
7. When I query the CP service for ADC value, it is in the neighborhood of 3750 (_0xEA6_)
8. I changed from 5V USB power to a programmable DC power supply and the results were effectively the same. Power rail and CP signal looked a little cleaner, but the behavior was the same.
9. This problem does not occur if I place a 2k7 resistor between CP&PE: i.e. no random toggling between states

### Remarks
1. Perhaps hysteresis around CP state threshold voltages should be implemented?
   - If there is already hysteresis for state changes, perhaps the hysteresis limits need to be widened?
   - I actually already made this observation to the CODICO engineer, and I believe this is what triggered a firmware update. However I am running the latest firmware version, yet the problem persists. 
2. Perhaps the ADC reading for CP needs to be digitally filtered?
   - I can only measure the voltage at the CP and PE connector, and I can see there is some periodic event that happens at every 40ms and the duration of this event is about 500us. This event happens even without initializing any of the services. It starts after Whitebeet comes up out of reset and persists.
   - See scope capture images _CP_event_period_ and _CP_event_duration_
   - This event absolutely looks intentional, due to the highly periodic nature and characteristic of the signal, but I wonder if it is possible that this activity on CP causes enough fluctuation on the ADC to tip the state machine into a new state?

#### CP_event_period
![CP_event_period](https://user-images.githubusercontent.com/29818706/138142614-bb0b3d81-f614-4e9b-ba50-d387009ddda7.jpg)
#### CP_event_duration
![CP_event_duration](https://user-images.githubusercontent.com/29818706/138142612-020d0273-f498-47c3-bf6e-81af4736714b.jpg)

**Comment by jpo-stx** [comment]
@zacharyalutz , there is a new Whitebeet firmware available which solves the issue. Please get in contact with Codico to get the latest firmware version.
