### ISSUE TITLE
Question Regarding the use of the SLAC/Bridging (EV) WB-CARRIER-BOARD-PS

### ISSUE THREAD

**Issue by JPiruzza** [Sevenstax/FreeV2G#117]
I have a question regarding the use of the SLAC/Bridging (EV) WB-CARRIER-BOARD-PS.

In the datasheet it says that after the SLAC process is completed all MAC frames will be forwarded to the PLC interface (see below). 

Does this mean that you cannot control the CP Line Voltage through the ethernet Interface after the SLAC process? Or is there a process to control the CP line after the SLAC process through ethernet. 

![image](https://user-images.githubusercontent.com/119959821/206508035-719d9e68-e09e-448c-b3e1-64a6126fce92.png)

**Comment by jpo-stx** [comment]
You can still send control messages to the Whitebeet by using it's MAC address.

Only MAC frames where the destination MAC adresss does not match the Whitebeet's MAC address are forwarded to the PLC interface.
