### ISSUE TITLE
ISO 15118-20 Support

### ISSUE THREAD

**Issue by st4hli** [Sevenstax/FreeV2G#145]
Hi,

the ISO 15118-20 has been released in April 2022. Will there be a Firmware update which adds the bidirectional charging functionality? If yes, when will this happen?

**Comment by lho-stx** [comment]
Hey @st4hli,

support for ISO 15118-20 is planned for 2024.

Thank you for your patience,
lho

**Comment by st4hli** [comment]
@lho-stx  Is there any update on this? Bidirectional charging is a very important feature which will only be available with ISO 15118-20
