### ISSUE TITLE
Broken _handleSessionError in Ev.py

### ISSUE THREAD

**Issue by st4hli** [Sevenstax/FreeV2G#146]
**Your Setup**
Platform: PEV
Firmware Version: i.e. V01_00_06
Host Controller Interface: Ethernet
Host: FreeV2G ([EV_v1.0.6_1](https://github.com/Sevenstax/FreeV2G/tree/EV_v1.0.6_1))

**Describe the bug**
The function _handleSessionError() in Ev.py, tries to get the error type from the message by using:
`errorType = message['error']` 
However, v2gEvParseSessionError only adds the key "code" to the message dictionary, so we don't get the error reason.

**To Reproduce**
Run into a 15118 session error.

**Expected behavior**
Correct message keys.

**Comment by nststx** [comment]
Hi @st4hli,

I was able to reproduce your issue. We indeed try to access the wrong key in that function. This issue will be fixed with the next version.

Best regards,
Niklas Stoffers
