### ISSUE TITLE
FreeV2G implementation/test code in C/C++

### ISSUE THREAD

**Issue by lb-rt** [Sevenstax/FreeV2G#163]
Hi, I'm starting working with the White Beet EI 1.1 via SPI and wanted to know if it’s possible to have some implementation or test code to run on a ARM MCU (STM32), so in C/C++ instead of python, even just for SPI/Framing protocol or at best also for SLAC/V2G.
Thank you.
Alberto

**Comment by lho-stx** [comment]
Hey @lb-rt,

we have plans for a port of FreeV2G to a C library and a example user application, to help customers with integration. We are in early stages of planning, so please don't expect that the library and the example user application are available soon!

If the library and example user application are available it will be announced in this repository! 

Thank you,
lho

**Comment by varshilgandhi** [comment]
Hi @AlbertoGilardoni-eaton,

I hope this message finds you well.

I saw your mention in this ticket about working on the FREEV2G implementation/test code in C/C++. I'm currently working on a similar task, porting Python source code into C for an MCU.

I was wondering if you had any experience attempting to port Python source directly into C++.  Any insights or suggestions you might have would be greatly appreciated.

Thanks in advance for your help!

Regards,
Varshil Gandhi

**Comment by varshilgandhi** [comment]
Hey @lho-stx ,

Yes Noted.

Thanks and Regards,
@varshilgandhi
