### ISSUE TITLE
DIN EVCC ID too long BMW i3

### ISSUE THREAD

**Issue by Dalachowsky** [Sevenstax/FreeV2G#165]
**Your Setup**
Platform: EVSE
Firmware Version: i.e. V02_00_01
Host Controller Interface: Ethernet
Host: FreeV2G (EVSE_v2.0.1_4)

**Describe the bug**
Whitebeet closes V2G session during session setup and reports "EVCC ID too long" in UART log.

**To Reproduce**
We have connected our Whitebeet module to BMW i3, and shortly after the end of SLAC matching the connection is dropped.

**Logs**
I'm attaching logs from whitebeet uart and port mirror, as well as logs from FreeV2G and pcap file from example communication session with BMW i3 that we have conducted
[2023_03_27_Log_vw_golf_EVCC_ID_error.zip](https://github.com/Sevenstax/FreeV2G/files/11076759/2023_03_27_Log_vw_golf_EVCC_ID_error.zip)
 using another SECC.

**Comment by lho-stx** [comment]
Hey @Dalachowsky,

thank you for the log files!

This issue seems to duplicate #164. If not please reopen the issue.

Thank you and best regards,
lho
