### ISSUE TITLE
Reading the Proximity Pilot on the WhiteBeet

### ISSUE THREAD

**Issue by dtomasi95** [Sevenstax/FreeV2G#179]
hello,
i was wonderning if there is a way to read the  Proximity Pilot status on the Whitebeet in EV mode to see if the innlet is mated whith an EVSE.

thank you,
best regard
d.tomasi

**Comment by lho-stx** [comment]
Hey,

@dtomasi95 unfortunately PP handling is not implemented right now.

Thank you,
lho

**Comment by dtomasi95** [comment]
and is there a plan to implement it at some point?
if yes can you tell me an estimate on when that would be?

thank you,
best regard
d.tomasi
