### ISSUE TITLE
User Manual r2.9: Request Start Charging   

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#18]
The definition for "Request Start Charging" does not match the example provided. I have outlined the problems below.

1. The table that associates the field name to the data type to a description of the field contains fewer entries than the example shows. For example, the field that follows "Start of profile from now on in seconds" is labeled "duration of this entry".  I have to assume "start of the profile from now on in seconds" is what the table refers to as "Start" (uint32), but according to the next line in the table we would expect the next entry to be "Power". However, in the description for "Charging profile entries count" a parameter named "Interval" is invoked, yet not discussed elsewhere in the table. On the other hand, going back to the example, we have "Duration of this entry" which seems to logically match the "Interval" field. This "Interval" field has been a component of the schedule tuple provided by the secondary actor (SA), so it makes sense to me that this field would still be included. In previous versions of this message, we had an 64-bit field called "time anchor" that seems to be similar in kind to the new field "Start" except half the size. 

2. "Schedule tuple ID" is advertised as a signed 16-bit integer, but appears to be 8 bits in the example. 
  a. Also, why is this field treated as signed number? Should we expect negative tuple IDs?  

3. "Charging profile entries count" is advertised as an unsigned 8-bit integer, but appears to be 16 bits in the example.  

Perhaps I am not being clear, but I am quite confused by this particular change. Ultimately all I want to know is how to correctly parse the message, and how to construct an appropriate response. I have attached a screenshot of the usermanual with some of my notes as a visual aid to provide more clarity. Thanks for your time.

![ReqStartCharging](https://user-images.githubusercontent.com/29818706/145088327-64ebbfc0-38cf-4635-abb7-7a3f9c423ce0.png)

**Comment by jpo-stx** [comment]
Hello @zacharyalutz ,

1. I will upload a new version of the manual where the example is fixed. The example should be:
```
C0 27 89 FF 00 16		(Req. Start Charging; ReqID: 255; Payload: 22 byte)
00 00 01 F4			(Timeout 500 ms)
00 01				(Selected schedule ID: 1)
02				(2 EV power profiles)
00 00 00 00			(Start of the 1st profile from now on in seconds)
00 16 03			(Power used in this entry)
00 00 0E 10			(Start of the 2nd profile from now on in seconds)
00 0B 03			(Power used in this entry)
01				(AC)
00 C1
```

2. "Schedule tuple ID" is 2 byte, as you can see in the example above.
We use sint16 because the DIN spec uses a short for the ID without a definition of the range. But you only need to expect the values that you set in your schedule for the ID.

3. "Charging profile entries count" is a uint8.

Hopefully this clarifies your confusion.

BR
Jan
