### ISSUE TITLE
V2G Service: Module ID mismatch in "White Beet User Manual r2.2"

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#2]
The module ID for the Vehicle to Grid (V2G) service is listed as two separate values in version 2.2 of the user manual. The table of module ID's lists it as 0x30, but the V2G chapter lists it as 0x27. I get a typical V2G-like responses using 0x27; What is the expected behavior? 

![image](https://user-images.githubusercontent.com/29818706/125353060-ad8f2000-e327-11eb-9425-f587c1959420.png)

![image](https://user-images.githubusercontent.com/29818706/125352801-538e5a80-e327-11eb-9690-900e871a122c.png)

**Comment by jpo-stx** [comment]
Hi @zacharyalutz,

The module ID for the V2G service in Table 19 is wrong. It should be 0x27 as it is stated in Chapter 15.

BR
Jan
