### ISSUE TITLE
what is the correct SPI max clock frequency

### ISSUE THREAD

**Issue by zhanglongqi** [Sevenstax/FreeV2G#204]
the max clock frequency is `8MHz` based on `9.2.1` in the manual.
but the code here is `12MHz`

https://github.com/Sevenstax/FreeV2G/blob/5718f0d4ca66958b2cc795812a580c17c8348608/SpiAdapter.py#L189C41-L189C41

**Comment by nststx** [comment]
Hi @zhanglongqi,

We recommend a maximum SPI clock frequency of `12Mhz`. However internally we tested boards for a frequency up to `24Mhz`. You can try a frequency greater than `12Mhz` but we do not guarantee stable operation for that. We'll also update the Manual regarding maximum SPI clock frequency.

If you have any questions left, please feel free to ask!

Best regards,
Niklas Stoffers
