### ISSUE TITLE
Question:GETTING FreeV2G issue

### ISSUE THREAD

**Issue by JIN-MIRAE** [Sevenstax/FreeV2G#206]
**Your Question**
Ask your questions here.

Hello,
I'm trying simulation test by using FreeV2G readme , but I have some problem.

First is that "source .venv/bin/activate" command dosen't practiced.
(error : 'soruce' isn't internal or external command, program for practice, or bat.file)

Second is that when I input command, "pip install python-libpcap", error happened as below image.
 
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/2769d1fd-4478-4f47-933a-bcd4d304bd38)
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/fc4c4d03-50cb-4af7-b9cd-dcdfdab05e13)

Thank you
Mirae

**Comment by nststx** [comment]
Hi @JIN-MIRAE,

Thanks for submitting your issue. The `source` command is a command specific to UNIX systems. On windows you just execute the *.bat* activation script to activate the virtual environment. If you run `python -m venv .venv` the activation script should be located under *.venv/Scripts/activate.bat*.
On Windows we also do not use the **python-libpcap** package. Instead please try to install the **scapy** package.

If you have any more questions, feel free to ask!

Best regards,
Niklas Stoffers

**Comment by JIN-MIRAE** [comment]
Hi, I tried again according to your comment, and it's successful.

And then I confirmed output, "Wait untill an EV connects", as below image.
![BOARDTESTCAPTURE](https://github.com/Sevenstax/FreeV2G/assets/129039253/f337ae61-32d5-43a0-8e7e-6b12aa623c8b)

But, I have another problem.
After seeing the output, I have to connect the PLC interface of the EV to the EVSE physically?
I don't know that how to connect EV & EVSE physically.
So, could you provide any guide?

Thank you
Mirae

**Comment by adirschl** [comment]
Hi Mirae,

I think you have two WHITEbeet Eval Boards. WHITEbeet-EI for EVSE side and WHITEbeet-PI for EV side. You physically connect the CP and PE pins of the boards, which means CP of the EI board to CP of the PI board and PE of the EI board to PE of the PI board. According to ISO15118-3 the PLC communication between EVSE and EV takes place over ControlPilot wire (CP) and PE wire. 

BR,
Andreas
CODICO

**Comment by JIN-MIRAE** [comment]
Yes. I did connected CP of PI & EI and PE of PI & EI.
![Connecting of PE   CP between PI and EI](https://github.com/Sevenstax/FreeV2G/assets/129039253/e591bd57-ae24-49da-aae4-fdc5cafd2fd3)

But, after connecting CP and PE, any additional output was not take placed.
Please let me know that what should I do.

Thank you

**Comment by adirschl** [comment]
Hi Mirae,
can you please measure the voltage between CP and PE on EVSE side before connecting and after connecting?
BR,
Andreas
CODICO

**Comment by JIN-MIRAE** [comment]
Hello Andreas,

Test condition is that:
1. EVSE was connected
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/6942e96f-ce70-4b56-853d-578a2a263ce5)
2. CP of EVSE is positive(+) and PE of EVSE is negative(-)
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/8969a266-bc80-437d-97bb-90fd5478e099)

A result is that:
Connected : AC 0.33V / DC -355mV
NOT Conncected : AC 0.73V / DC -0.6V

Is there a problem of voltage measurment?
If so, let me know that.

Thank you

**Comment by JIN-MIRAE** [comment]
I found a problem of voltage measurment, so I inform you.
The problem is that measured values are changing continuously.
Even if when I tried measurment directly on pin as below image, same problem happened.
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/874c6e7f-68b3-4fc2-9eee-a4b4409d157e)

**Comment by lho-stx** [comment]
Hey @JIN-MIRAE,

you should see a constant +12V when no EV is connected (actually it is a PWM signal with 1kHz and -12V to +12V peak to peak swing and 100% duty cycle). When an EV is connected, the voltage should drop to +9V (again,  18V peak to peak without a DC bias). Now there are three possibilities:

- the measurement was not done right (I do not think this is a problem here)
- you multimeter is faulty (I also do not think this is a problem)
- the whitebeet is faulty (what I think is the most likely)

Just to be sure:
If you can, connect the CP to a oscilloscope and see, if there is a PWM signal at all an what peak to peak voltage it has. To do this please change `self.whitebeet.controlPilotSetDutyCycle(100)` in Evse.py to `self.whitebeet.controlPilotSetDutyCycle(50)` and do the measurement. You should see a 1 kHz PWM with 50 % duty cycle, centered around 0V and with 18V peak to peak voltage.

Please feel free to share your oscilloscope measurement!

If there is no PWM at all, please get in touch with CODICO and please close this issue, as this is a problem not related to the Whitebeet firmware or FreeV2G software.

Thank you for contributing,
lho

**Comment by adirschl** [comment]
Hey @JIN-MIRAE,

as this seems to be not a software related problem please open a ticket at CODICO by writing an email to plc@codico.com.
please do following measurements:

1) voltage between CP and PE on the WHITEbeet-EI (in the unconnected state, **not connected** with WHITEbeet-PI)
-> you should measure +12V, if not here is a hardware problem on the WHITEbeet board.

2) all other measurements should be done by oscilloscope, as there will be a 1kHz PWM signal with different voltages and dutycycles present.
-> after connecting the WHITEbeet boards there should be a PWM with +9V and -12V (only the positive halfwave is reduced in voltage due to a serial diode in the EV circuitry), dutycycle dependant on the software settings.

BR,
Andreas Dirschl,
CODICO

**Comment by lho-stx** [comment]
Closing this issue, because it is not software related.
