### ISSUE TITLE
Charging BMW fails at precharge state

### ISSUE THREAD

**Issue by sametyazici** [Sevenstax/FreeV2G#207]
**Your Setup**
Platform: EVSE
Firmware Version: i.e. V02_01_00
Host Controller Interface: Ethernet
Host: Own Implementation

**Describe the bug**
We work on WB-CARRIER-BOARD-EI module and run FreeV2G. We are able to charge different brand Evs but fails at BMW brand EV. The EV send precharge request and we reach desired dc bus voltage value about 3 seconds. But then the EV stops the session.

**Expected behavior**
We are stuck just before charging request. The EV should send power delivery request after precharing but it didn't.

**Logs**
In the bmw_precharge_fails.zip, there are two log file:
bmw_precharge_fails.txt is a log from the serial port of the WB-CARRIER-BOARD-EI board
bmw_precharge_fails.pcapng is log from wireshark of between host and WB-CARRIER-BOARD-EI board. They are isolated from LAN
[bmw_precharge_fails.zip](https://github.com/Sevenstax/FreeV2G/files/12228540/bmw_precharge_fails.zip)

**Comment by sametyazici** [comment]
Any suggestion?

**Comment by sametyazici** [comment]
In addition BMW ix3 only accept DIN standart.

**Comment by lho-stx** [comment]
Hey @sametyazici,

thank you for using our template and providing the requested logs. I will have a look into the logs and come back to you as soon as possible!

Best regards,
lho

**Comment by sametyazici** [comment]
We have another log of debug port and ethernet port of same charging session.
[bmwix3_prechargefails.zip](https://github.com/Sevenstax/FreeV2G/files/12249138/bmwix3_prechargefails.zip)

**Comment by sametyazici** [comment]
For your reference I add another pcap log which is a successful charging session of Reanult Zoe model.
With the same setup, we failed to charge BMWix3.

For your attention; both sessions (BMW and Zoe) are in DIN protocol because BMW requests only DIN protocol. 

[bmwix3_prechargefails.zip](https://github.com/Sevenstax/FreeV2G/files/12251496/bmwix3_prechargefails.zip)
[zoe_DIN.zip](https://github.com/Sevenstax/FreeV2G/files/12251445/zoe_DIN.zip)

**Comment by sametyazici** [comment]
Are there any progress in your side? This issue is so frustrating and we still have no idea what we are do wrong. We need your urgent assistance as soon as possible.

**Comment by lho-stx** [comment]
Hello @sametyazici,

thank you for trying with another EV as reference! I checked your log files and it seems the BMW reports an error:

DC EV Error Code: Failed - RESS Temperature Inhibit (1)

Please see the screenshot:

![bmw-pre-charge-req-error](https://github.com/Sevenstax/FreeV2G/assets/103272216/3c238e8e-1c87-4681-bdc6-3111068587a9)

In case of Zoe everything is ok:

![zoe-pre-charge-req-ok](https://github.com/Sevenstax/FreeV2G/assets/103272216/2760b9b5-0cc2-447b-8d39-d689e698fcb4)

Please check the RESS on EV side, it seems there is a problem with it.

Best regards,
lho

**Comment by sametyazici** [comment]
Hi, 
Thank you very much for your reply.
As stated in White Beet - User Manual (Revision No.: 2.16),  section 18.12.6 DC Charge Parameters Changed; WB should report us the "RESS Temperature Inhibit" error in 0x85 DC Charge Parameters Changed message.

![image](https://github.com/Sevenstax/FreeV2G/assets/9167377/b9e82405-8e62-4dcd-97ad-62b74fc67511)


We modified the code as below to print error message from EV side in v2gEvseParseDCChargeParametersChanged function.

![image](https://github.com/Sevenstax/FreeV2G/assets/9167377/6ad6bbcb-7919-4bd7-8fd0-d76d1243aa47)


From our terminal logs we see **_no error reported from WB_** in v2gEvseParseDCChargeParametersChanged function.
So we conclude that WB may be ignoring this error code or your dissector may be wrong interpretting the message from EV!

Please also note that we can charge the BMWix3 without problems in public charging stations so any hardware problem with RESS is a very low probabilty.

Best regards.

**Comment by lho-stx** [comment]
Hey @sametyazici,

Thank you for clearifying. I will double check the firmware and the dissector and will come back to you as soon as possbile!

Best regards,
lho

**Comment by sametyazici** [comment]
Thanks. We are waiting for next explanation.

**Comment by lho-stx** [comment]
Hey @sametyazici,

we do not have instantly access to every EV on the market, therefore we do not have a log file for this specific model. 

I am currently working on a solution to get the Whitebeet in the exact same state as yours (following the messages in the log file), so I can identify possible problems in the firmware. My colleague is double checking for possible errors in our dissector right now. Please allow some time to investigate this issue with the necessary attention.

Thank you for your patience and best regards,
lho

**Comment by ColinCGC** [comment]
It might not be your problem, but we did run into a similar sounding issue (on the i3) - it uses DIN and DIN has a much shorter timeout for the PowerDeliveryReq response - I think around 1.5s, compared to the 5s for ISO.

I haven't looked at your logs so I don't know if PowerDeliveryReq is being sent or not, but if it is and the EVSE does not enable its output and send a response quickly enough after precharge then the sequence will terminate.

**Comment by sametyazici** [comment]
We were connecting resistance between PP and PE. This prevented us from proceeding after precharge. It worked when we removed the resistor.
