### ISSUE TITLE
PnC support

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#22]
@ttu-stx,

Earlier this year I inquired about TLS and you mentioned future firmware version where PnC is supported:

> Hi Zach,
for ISO15118-2 EIM TLS is not mandatory and thus not supported in the current White Beet. We will release a White Beet EVSE PnC Version where TLS is supported for both PnC and EIM.
BR

_Originally posted by @ttu-stx in https://github.com/Sevenstax/FreeV2G/issues/12#issuecomment-948367935_

To that end, do you know when firmware with PnC support will be available? I am eager to integrate Whitebeet into our metering platform and validate the message sequencing.

Thanks,
Zach

**Comment by ttu-stx** [comment]
White Beet EVSE PnC Release is planned for Q1/22.
