### ISSUE TITLE
 Question: Setting parameter of EVSE & EV

### ISSUE THREAD

**Issue by JIN-MIRAE** [Sevenstax/FreeV2G#224]
**Your Question**
Ask your questions here.

Hi,

I hope to know a way to change parameter manually like EVCC ID, current , voltage and etc..
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/d499cd6f-f1ef-446f-bec6-c69b5fc66d72)

I tried setting by using serial program, however that didn't worked.

So I don't know how to change and set the values.

Is there a tool or something for setting parameter of board?

Thank you
Mirae

**Comment by lho-stx** [comment]
Hey @JIN-MIRAE,

the so called Framing protocol can be used via ETH or SPI only (unfortunately no UART support). You can clone this repository to a Linux or Windows PC and use Python to run the FreeV2G Application. It will use ETH or SPI for communication with the Whitebeet module. Please see the README of this repository for more information and how to get started.

Best regards,
lho
