### ISSUE TITLE
V01_01_06 Tesla model 3 stops @ V2G start with DIN or no ev_target_current and stopping in iso 

### ISSUE THREAD

**Issue by JGitSchel** [Sevenstax/FreeV2G#226]
Tesla model 3 connecting with firmware v010106:
- Protocol[2] -> ev_target_current keeps 0 in precharge and charge loop parameters
- Forced it in pre-charge to 1.0 amps and in charge loop to max current, but then the first message received is 499A max ev current, but the next is 9.0 and then 'stop received'
- In Protocol[0] the module doesn't get further than V2G start.. it just times out. 

Audi e-tron and peugeot does charge, so what could be the problem with Tesla?

**Comment by lho-stx** [comment]
Hey @JGitSchel,

thank you for contributing, but please use the issue template and provide all information and logs we ask for. If you have problems creating the log files, please let me know. 

Closing this issue until requested information was added.

Thank you,
lho
