### ISSUE TITLE
Question: Setting parameter of EVSE ID

### ISSUE THREAD

**Issue by JIN-MIRAE** [Sevenstax/FreeV2G#228]
**Your Question**
Ask your questions here.

Hi,

You said I have to modify 'evse.config dict' like image.
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/6502f430-6ed8-44db-b1d0-fc50aed15140)

But  I don't know what means 'ense.config dict' exactly.
![image](https://github.com/Sevenstax/FreeV2G/assets/129039253/fec6a234-f337-48a6-a978-a8f55395d6bd)
Is that part right? Should I modify that 'dict' for setting EVSE ID?

Thank you

**Comment by lho-stx** [comment]
Hey @JIN-MIRAE ,

Let's move the discussion to the other issue. No need to create a new issue for every single question!

Best regards,
lho
