### ISSUE TITLE
Question: no doc for module id 0xFF

### ISSUE THREAD

**Issue by zhanglongqi** [Sevenstax/FreeV2G#229]
I received a frame but no document for this module id (0xFF)

![image](https://github.com/Sevenstax/FreeV2G/assets/956693/309b2ef1-1508-42cf-9b7a-ac36a876bcfd)

![image](https://github.com/Sevenstax/FreeV2G/assets/956693/3b7b46ad-f754-4992-9030-ad582725a9ab)

**Comment by lho-stx** [comment]
Hey @zhanglongqi,

modId 0xFF is tied to the framing module itself. SubId 0xF3 is "Status Missing End Of Frame". This is send when the end of frame byte in the last message to the Whitebeet is missing. Please check if the last message you send to the Whitebeet is malformed!

I will discuss internally if the information about this module will be added to the Whitebeet manual.

Best regards,
lho

**Comment by zhanglongqi** [comment]
Thanks, found the bug already.

This information is very important for the application development. Hiding this will only drag our process.

**Comment by lho-stx** [comment]
Good to hear you made progress!

I understand your point and will communicate it internally!
