### ISSUE TITLE
'Download PIB without reset' or 'EV in wrong state' how to solve?

### ISSUE THREAD

**Issue by JGitSchel** [Sevenstax/FreeV2G#230]
In both evse FW 1.6 and 2.1 (with host software 1.06 and the actual master) when closing down the software and restart a session, SLAC always times out.
I've connected the serial interface and read 'Download PIB without reset' or 'EV in wrong state', then the EV keep silent until either reconnect the cable or lock/unlock.
This is with an Audi e-tron. 
My question is, is there a command to send before SLAC to reset the car.
It happens after the precharge is started, before that moment, this does not happen. 
I added some extra stop functions: slacstop, CP stop etc. but doesn't solve this issue. 

(to forecome multi threads here, note to the master software -> dictionary DC parameters-> please add int() becasue floating points can't be indexed'... maybe a newbe software engineer could get in trouble here...)

**Comment by lho-stx** [comment]
Hey @JGitSchel,

please use the issue template ("New issue">select bug report> read and fill the template) and provide all information and logs we ask for, else we can not support your case. We can not investigate such issues without the template being filled completly. If you have problems creating the log files, please let me know.

Closing this issue until requested information was added.

Best regards,
lho
