### ISSUE TITLE
typo in 18.10.13 Set Schedules

### ISSUE THREAD

**Issue by zhanglongqi** [Sevenstax/FreeV2G#234]
should be `uint16` right?

![image](https://github.com/Sevenstax/FreeV2G/assets/956693/cd7a5667-1651-4096-a0cd-eefa8ff69df1)

**Comment by nststx** [comment]
Hi @zhanglongqi,

Thanks for submitting your question. The schedule tuple ID is actually of type `sint16` and not `uint16`. This is required by the ISO15118-2 standard. The standard only restricts the SAID type to short and not to unsigned short. Thus the type in the table is correct. Although I've never seen an ID with a negative ID it should theoretically be possible.

I hope I could clarify your question. If you have any more questions, feel free to ask! If you consider this resolved, please close the issue.

Best regards,
Niklas Stoffers
