### ISSUE TITLE
Loss of communication at datalink layer

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#24]
Requirements for loss of communication with respect to SLAC and CP are defined in ISO 15118-3 in section 7.5. I am wondering if these requirements are satisfied internally by Whitebeet or if it is up to the host? Here's an example of what I'm talking about:

![image](https://user-images.githubusercontent.com/29818706/146659739-68913a5e-6e8c-49c0-91a7-9e65b26531c5.png)

Thoughts?

**Comment by bbr-stx** [comment]
These requirements are the responsibility of the host. The Whitebeet does not change the CP state by itself, it requires the control via the HCI interface.
