### ISSUE TITLE
open-plc-utils

### ISSUE THREAD

**Issue by Fatih738** [Sevenstax/FreeV2G#240]
Can I write a code using open-plc-utils commands. I want to communicate with red-carrier-board p over raspberry pi using open-plc-utils. Can I write a charging scenerio as a pev side with open-plc-utils

best wishes

**Comment by lho-stx** [comment]
Hey @Fatih738,

if you disable SLAC service and V2G service (or just powercycle the Whitebeet) you can use the QCA700x with open-plc-utils. Please keep in mind we can not offer support for this use case, but I can tell you that I tested this setup and did a SLAC matching with two Whitebeets and open-pl-utils.

Best regads,
lho
