### ISSUE TITLE
BMW iDrive 50 + Polestar 'session stopped' after start charge

### ISSUE THREAD

**Issue by JGitSchel** [Sevenstax/FreeV2G#241]
**Your Setup**
Interface: Whitebeet carrier board (WB-CARRIER-BOARD-EI)
Platform: EVSE
Firmware Version: i.e. V02_01_00
Host Controller Interface:  SPI
Host: FreeV2G (Master from SevenStax Git, implemented in own code)

**Describe the bug**
After precharge BMW iDrive 50 and Polestar send session stopped. 
BMW directly (EV's relay not activated, so not even current - so DC measured output keeps 0.0A), Polestar starts relay, after three messages (_handleDCChargeParametersChanged) with increasing currents 1.0, 2,1A, 3.4A [current is also measured on DC output) Session Stopped is received. 
BMW does not even start charging.. it directly sends an session stopped. 

**To Reproduce**
See attached log for charge steps.
I've tried a lot (for example, send setpoint voltage in case the read voltage is not within spec for the EV, send modified charge current for same reason, add more processorspeed etc. but every time at the same point bot EV's send Session Stopped.

**Expected behavior**
With other EV brands the session starts with 1.0A precharge and then increases to max power.

**Logs**
Log of own code + debug FTDI interface whitebeet 
[?] We are using SPI, mirror is enabled, I see a lot of homeplug+TCP messages over eth0, is this you need as log too?

**Additional c
[Log_18-9-2023_Own code.zip](https://github.com/Sevenstax/FreeV2G/files/12647207/Log_18-9-2023_Own.code.zip)
[Log_18-9-2023_Own code.zip](https://github.com/Sevenstax/FreeV2G/files/12647210/Log_18-9-2023_Own.code.zip)
ontext**

**Comment by lho-stx** [comment]
Hey @JGitSchel,

thank you for using the template.

From the UART logs I can read, that there is a session error. I need to have a look into the network traffic. Can you please create a wireshark log? We have a guide for this, you can find it [here](https://github.com/Sevenstax/FreeV2G/wiki/guide-creating-log-files).

Thank you and best regards,
lho
