### ISSUE TITLE
Question: Error installing python-libpcap

### ISSUE THREAD

**Issue by DDEVBuddy** [Sevenstax/FreeV2G#242]
**Your Question**
Ask your questions here.
Hi -

Have whitebeet eval board and setting up Free2VG first time on a windows 10 computer, following instructions I am running in to the error while attempting to run pip install python-libpcap (npcap also successfully installed).  See below - let me know if you can offer any guidance. Thanks.

===========================================================
C:\WINDOWS\system32>pip install python-libpcap
Collecting python-libpcap
  Downloading python-libpcap-0.4.2.tar.gz (81 kB)
     ---------------------------------------- 81.2/81.2 kB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Cython>=0.29.23 in c:\users\cwcm\appdata\local\programs\python\python311\lib\site-packages (from python-libpcap) (3.0.2)
Building wheels for collected packages: python-libpcap
  Building wheel for python-libpcap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for python-libpcap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      C:\Users\CWCM\AppData\Local\Temp\pip-build-env-wn_k4red\overlay\Lib\site-packages\setuptools\dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\cli.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\exception.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\open.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\parse.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\pcap.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\utils.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\__init__.py -> build\lib.win-amd64-cpython-311\pylibpcap
      copying pylibpcap\__main__.py -> build\lib.win-amd64-cpython-311\pylibpcap
      running egg_info
      writing python_libpcap.egg-info\PKG-INFO
      writing dependency_links to python_libpcap.egg-info\dependency_links.txt
      writing entry points to python_libpcap.egg-info\entry_points.txt
      writing requirements to python_libpcap.egg-info\requires.txt
      writing top-level names to python_libpcap.egg-info\top_level.txt
      reading manifest file 'python_libpcap.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.h' under directory 'src'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file 'python_libpcap.egg-info\SOURCES.txt'
      copying pylibpcap\base.c -> build\lib.win-amd64-cpython-311\pylibpcap
      running build_ext
      building 'pylibpcap.base' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-libpcap
Failed to build python-libpcap
ERROR: Could not build wheels for python-libpcap, which is required to install pyproject.toml-based projects

C:\WINDOWS\system32>
===========================================================

**Comment by lho-stx** [comment]
Hey @DDEVBuddy ,

`python-libpcap` is not needed on Windows, this is an error in the README. Skip this package on Windows.

Best regards,
lho
