### ISSUE TITLE
doc and code are not consistent

### ISSUE THREAD

**Issue by zhanglongqi** [Sevenstax/FreeV2G#245]
**Your Setup**
Platform: EVSE
Firmware Version: i.e. V02_00_01
Host Controller Interface: Ethernet
Host: FreeV2G

**Describe the bug**

what the relationship between system version and firmware version? it's confusing.

![image](https://github.com/Sevenstax/FreeV2G/assets/956693/c163775a-c716-46aa-a452-99e282453245)

![image](https://github.com/Sevenstax/FreeV2G/assets/956693/a1857a8f-da7c-47d7-acb7-a9afcd2875bb)

![image](https://github.com/Sevenstax/FreeV2G/assets/956693/ef38caf4-ccaf-4fef-b5a9-f260852129ee)

**Comment by lho-stx** [comment]
Hey @zhanglongqi,

I admit it is confusing. The `Get Version` command gets the version of the filesystem in the FWU file used to update the Whitebeet. The `Get Firmware Version` gets the actual version of the running firmware (v02.0.01 in your case). The `Get Version ` is not relevant and will be removed from the manual.

Thank you for pointing out!
lho
