### ISSUE TITLE
EVSE does not work with Hyundai KONA 

### ISSUE THREAD

**Issue by zhanglongqi** [Sevenstax/FreeV2G#248]
**Your Setup**
Platform: EVSE
Firmware Version: V02_00_01
Host Controller Interface: Ethernet
Host: FreeV2G (EVSE) EVSE_v2.1.0_1)
 
 Host controller Interface: ETHERNET!

**Describe the bug**
The same FREEV2G program and same hardware setup, it only works with IONIC 5 but not with KONA.
![2023-09-27_18-30](https://github.com/Sevenstax/FreeV2G/assets/956693/d0d0644a-7d31-467b-bacf-47cc57242675)

The Kona I use works well with [SP 100 kw charger](https://carbuyer.com.sg/sp-group-charge-your-ev-singapore/). 
![image](https://github.com/Sevenstax/FreeV2G/assets/956693/cd867224-da6c-40c4-a6e7-acc5a11c81a6)

I tried DIN only and ISO15118 only, both do not work.
![2023-09-27_18-23](https://github.com/Sevenstax/FreeV2G/assets/956693/fb86561d-5414-4de0-a3c9-e03cc724feb2)
![2023-09-27_18-26](https://github.com/Sevenstax/FreeV2G/assets/956693/66430a61-aeee-4d07-8631-5606b9d06b9e)

**Logs**
[kona-iso15118-2023-10-27.zip](https://github.com/Sevenstax/FreeV2G/files/12744934/kona-iso15118-2023-10-27.zip)

**Comment by lho-stx** [comment]
Hey @zhanglongqi,

you configured your Whitebeet to support ISO only:

![setupwhitebeet](https://github.com/Sevenstax/FreeV2G/assets/103272216/c86bd899-9432-4d20-b371-701cd33398e8)

The Hyundai Kona only offers DIN:

![supportedappreq](https://github.com/Sevenstax/FreeV2G/assets/103272216/544f1ad4-e0f5-4551-b437-9660c9e66338)

Try to enable DIN for your Whitebeet too. This should fix your issue!

I want to ask you for a favor:

The next time you are testing the Ionic 5, can you create a wireshark log of the working charging session? We had issue with some Ionic 5 in the past and try to figure out why some are failing the charging session for no good reason and why the most do not.

Best regards,
lho

**Comment by zhanglongqi** [comment]
I tried  DIN only but it did not work and the error is showed in the screenshot marked as "Kona, DIN only"

**Comment by zhanglongqi** [comment]
I have it before. 
It's 7z file actually. github do not allow 7z file uploading.
[ionic-5-no-DIN.7z.txt](https://github.com/Sevenstax/FreeV2G/files/12774075/ionic-5-no-DIN.7z.txt)
