### ISSUE TITLE
FW Upgrade on EVSE Module

### ISSUE THREAD

**Issue by pranavsparalikar-eaton** [Sevenstax/FreeV2G#260]
Hi,

I have a WB EVSE module with FW version V01_01_07 (EVSE Dev. Kit) and I want to upgrade its FW to version V02_01_00. I initially followed the steps given in the White Beet - User Manual v2.16. I have used ‘WHITEBEET_ISO15118_EVSE_V02_01_00.fwu’ available on CODICO site.

Based on the procedure, I have encrypted the FW file. Following is the screenshot of the config script. The default signing key shared along with the binaries, is used for signing the FW.

![1](https://github.com/Sevenstax/FreeV2G/assets/136327877/17e9716e-e4c2-43da-8ba1-f45ab1f7a9a8)

The following commands were used for updating the FW to the EVSE side CODICO module:
1.	$./StxFwGen.py -k SigningCert.key -c fwu_config_01.py -o WHITEBEET_ISO15118_EVSE_V02_01_00.fwu
2.	$sudo ./FWUtool.py -f WHITEBEET_ISO15118_EVSE_V02_01_00.fwu -t (Dev. Kit MAC Add.) -i eno1
Below was the response received from the module once the update was completed (pls. note, the file used for update was signed and encrypted only):

![2_1](https://github.com/Sevenstax/FreeV2G/assets/136327877/6ca7a040-c3b6-4e23-b51c-f4eaec286fbf)

After this, to check whether the FW update of the CODICO module is successful or not, I connected the UART port to my Laptop and tried to read the FW version through the debug messages. Pls. refer the screenshot below:

![3](https://github.com/Sevenstax/FreeV2G/assets/136327877/7a0f770a-11d8-4bc0-bbbc-e50187d7775a)

It can be seen that, the FW version V01_01_07 is not updated to V02_01_00 and some error is also encountered at the time stamp of 5.612s.

Here, I realized the mistake I had done and then tried uploading the  WHITEbeet module with the original FW (WHITEBEET_ISO15118_EVSE_V02_01_00.fwu), which I had downloaded from the CODICO site. Pls. note, this is the same module on which, I had updated the FW with default signing key. The FW was updated successfully without any error, it can be seen in the debug messages. But the same error at 5.8s is encountered. The debug messages are stopped at this point. Pls. refer the screenshot below for your ref.:

![4](https://github.com/Sevenstax/FreeV2G/assets/136327877/dda79791-5d8d-494b-9fbd-b70db7296f20)

If I connect an ethernet cable to the Dev. kit., messages shown in screenshot below are seen:

![5](https://github.com/Sevenstax/FreeV2G/assets/136327877/d52b9ab3-a910-4b0e-893f-865f8def08a4)

Request you to have a look and suggest a way ahead.

--
Thanks & Regards,
Pranav

**Comment by lho-stx** [comment]
Hey @pranavsparalikar-eaton,

I need to discuss this issue with a colleague. I will come back to you as soon as I have news.

Best regards,
lho

**Comment by jpo-stx** [comment]
Hello @pranavsparalikar-eaton ,

you created a firmware update file, which overwrites the QCA firmware with the Whitebeet firmware. Have a look at your fwu_config_01.py at source and destination.

You should take the WHITEBEET_ISO15118_EVSE_V02_01_00.fwu as it is and upload it.

Now you would need to create a fwu file with the QCA firmware.

**Comment by pranavsparalikar-eaton** [comment]
Hello @jpo-stx @lho-stx ,

Thanks for your reply. 

I followed the procedure given in the WB user manual and was able to upload the QCA FW successfully. Now the VFS ERROR seen in earlier screenshots is not there, but there is still a continuous message "IF not linked" seen on the terminal. Pls. refer screenshots below in case of SPI as well as Ethernet:
![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/4d1d497b-5207-4a26-98b3-0dbb52666cc9)

![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/39a82bf7-44af-419c-a96a-6e81d7b26ef5)

Pls. advise on this. Where or what have I missed...?

--
Thanks & Regards,
Pranav

**Comment by pranavsparalikar-eaton** [comment]
Hello @jpo-stx @lho-stx,

I have shipped this module to CODICO for reprogramming. So, I am closing this issue.

--
Thanks & Regards,
Pranav
