### ISSUE TITLE
Didn't receive a frame before the timeout of 30s.

### ISSUE THREAD

**Issue by ChaiyotMix** [Sevenstax/FreeV2G#262]
**Your Setup**
Platform:  EVSE
Firmware Version: i.e. V02_01_00
Host Controller Interface: Ethernet
Host: FreeV2G 

Platform: PEV
Firmware Version: i.e. V01_00_07
Host Controller Interface: Ethernet
Host: FreeV2G

**Describe the bug**
I just tried to successfully update the firmware to the latest version and then tried to use Free V2G again and found that it still cannot be used until the end of the program, with an error occurring on the EVSE side saying "We did not receive a frame before the timeout of 30s"

**Expected behavior**
I would like to test the EVSE and PEV boards to be able to use the Free V2G program successfully first.

**Logs**
This is the message that appears in the command prompt on both the EVSE and PEV sides.
[Error.txt](https://github.com/Sevenstax/FreeV2G/files/13447007/Error.txt)

**Additional context**
This is the experimental picture.
![2](https://github.com/Sevenstax/FreeV2G/assets/102137530/e6b7704f-cc62-41b5-9a92-07464a991218)

**Comment by lho-stx** [comment]
Hey @ChaiyotMix,

Can you please create wireshark logs of the session? There is a guide to create these logs [here](https://github.com/Sevenstax/FreeV2G/wiki/guide-creating-log-files).

Best regards,
lho
