### ISSUE TITLE
EV and EVSE eval boards don't connect past SLAC matching

### ISSUE THREAD

**Issue by Kristanpivk123** [Sevenstax/FreeV2G#263]
Platform: PEV and EVSE
Firmware Version: i.e. V01_00_06 and V02_01_00
Host Controller Interface: Ethernet 
Host: FreeV2G (latest pull)

I am trying to connect two WHITE beet carrier boards (EV ISO15118 for WHITE beet PI 1.1 and EVSE SIO15118 for WHITE beet EI 1.1) with a desktop PC and laptop using your Python scripts. It worked until a few days ago when I tried to make a log with wireshark on laptop. Ever since then I was not able to achive the charging.
If I have my laptop connected to EV board and PC to EVSE, the session on EV (laptop) freezes when it gets to the "Start SLAC matching" message. On EVSE (PC) it sends the message "SLAC matching successful" and continues to start the V2G (message "Start V2G"). After 30 seconds it stops the loop because of timeout, but when it times out, the EV starts to continue and says SLAC connected.
I tried running EV on PC and EVSE on laptop and it wasn't consistent; sometimes it actually got to the pre-charging then stopped the session but sometimes it did the same problem as described above. The inconsistency was also present when EV was laptop and EVSE was PC, but a lot more consistent.
When I tried to update both boards, I successfully updated EVSE. EV, on the other hand, rejected update files for V01_00_07. Update powershell messages:

Welcome to the SEVENSTAX FWU Tool 2.6

Initiating framing interface
Starting update process
Firmware update at 0 percent; Sent: 833 Bytes
[!] Error: Device rejected update file

I created logs in wireshark for PC and logs in terminal for laptop. Logs from wireshark for PC communication are in a zip
[EV_log_on_laptop.txt](https://github.com/Sevenstax/FreeV2G/files/13634389/EV_log_on_laptop.txt)
[EV_log_on_laptop_2_orig_problem.txt](https://github.com/Sevenstax/FreeV2G/files/13634395/EV_log_on_laptop_2_orig_problem.txt)
[EVSE_log_on_laptop.txt](https://github.com/Sevenstax/FreeV2G/files/13634396/EVSE_log_on_laptop.txt)
[for PC logs (wireshark).zip](https://github.com/Sevenstax/FreeV2G/files/13634409/for.PC.logs.wireshark.zip)

**Comment by lho-stx** [comment]
Hey @Kristanpivk123,

Thank you for using the template!

I checked the Wireshark logs and it seems the MAC address of your Laptop/PC is set to 00:00:00:00:00:00. This is an invalid MAC and the Whitebeet answer to this MAC with broadcast messages. Can you check the MAC address of the interface used on your Laptop/PC is actually valid?

Best regards,
lho

**Comment by Kristanpivk123** [comment]
Thank you for your answer.
I hope I understood your instructions correctly: I checked MAC on my PC and laptop from cmd->ipconfig/all.
PC: Physical Address. . . . . . . . . : C8-7F-54-A8-30-92
Laptop: Physical Address. . . . . . . . . : F4-A8-0D-B4-DF-92
I should point out that I changed my laptop, but the problem was still the same when I changed it.

I should also say that I was able to overcome the problem today; I managed to make a session go through. I found out that if I use npcap 1.76 instead of npcap 1.78 on both computers (it might only be mandatory on the cmputer that is running EV WHITE beet), it works to some degree (it still varries depending on which computer is driving which WHITE beet: PC=EV and laptop=EVSE works, the other way around it stops the session right before the charging is started; If I use an additional laptop and have one laptop=EV and the other laptop=EVSE it works, even if I switch their roles around). 

But I still can't update the WHITE beet, so that problem is still present.

**Comment by lho-stx** [comment]
Hey,

interesting find. Problems with Windows machines are common, often due Windows being inconsistent with networking (due to driver version, OS version, company guidelines). If possible try a Linux based machine and see if there are similar issues...

Also, can you please create a wireshark and uart log of the failed firmware update session?

Best regards,
lho

**Comment by Kristanpivk123** [comment]
Hey, Iho

I don't have a Linux machine to use, but I am currently trying to install a virtual machine with Ubuntu 22 and I'll see how it goes.

I also made the log. I tried to update it without an UART connected and with UART connected (first time around I forgot to add UART logging); I got a bit different log when I added UART so that's why I'm adding two wireshark logs and one UART log
[EV_failed_update.zip](https://github.com/Sevenstax/FreeV2G/files/13682706/EV_failed_update.zip)

Best regards,
Kristan Pivk

**Comment by Kristanpivk123** [comment]
Hi, 
should I add any other log?

Best regards,
Kristan

**Comment by lho-stx** [comment]
Hey @Kristanpivk123,

no it was only the github bot auto labling this issue. Please allow a bit more time for analyzing this issue.

Best regards,
lho

**Comment by lho-stx** [comment]
Hey @Kristanpivk123,

just for my sanity: you are on PEV FW 1.0.6? Did you get the firmware file before 27th of June 2023?

Best regards,
lho

**Comment by kristanpivk** [comment]
Hey, Iho,
I used the latest update file on Codico server and the current software should be V1.0.6 for PEV.
Currently I am out of office. I'm returning on Monday, 22.1.2024. I'll check then to be sure and get back to you.
Best regards,
Kristan

**Comment by Kristanpivk123** [comment]
Hi, Iho,

I checked again:
- I'm using WHITE beet PI 1.1 with V01.00.06 on it currently
- I downloaded the update file for EV V01.00.07 and the FWU tools on 11.12.2023 from CODICO PLC documentation area
- update tool has date 10.5.2023 in its name
- I tried to update again and WB rejected the update file
- I connected computer directly to WHITE beet over ethernet
- if it helps, I'm adding the FWU file I used and logs from Powershell, UART terminal and Wireshark
[Failed_update_files.zip](https://github.com/Sevenstax/FreeV2G/files/14006371/Failed_update_files.zip)

Best regards,
Kristan

**Comment by lho-stx** [comment]
Hey @Kristanpivk123,

I think I know what's off. There was an issue with the v1.0.6 EV firmware. The issues was that you are not able to upgrade your board anymore. Normally Codico should have contacted you, if you bought an affected board. There is also a Disclaimer in the repository, that is warning about this specific FW version. If you bought the board with v1.0.6 or you did upgrade it yourself and now it is bricked, please get in touch with Codico to get a replacement.

Thank you for your patience and time,
lho

**Comment by Kristanpivk123** [comment]
Thank you, Iho, I'll do that.

Best regards,
Kristan

**Comment by Hipowerguy** [comment]
Hello Kristanpivk123  

I am having a similar issue with my two White Beet (WB) boards, one EVSE V2.1.0 and the other one EV V1.0.7.
Both are running from one Raspberry Pi 4 board running Debina (Linux).  I open a different instance of FreeV2G for each WB and it seems to work until connection on V2G mode.  The EVSE board times out after 30 seconds just like you describe above.

I read with interest Iho's suggestions and the work that you did but I am puzzled as to why the Ethernet connection would have an effect on the EVSE timing out when waiting for the EV.  
Did you figure out why?  
Have you had any success in producing a reliable setup?

Thanks,

Marco

P.S. The attached picture gives both monitors.
![20240414_150440 1](https://github.com/Sevenstax/FreeV2G/assets/91483540/8782e3af-24a5-45cd-85c5-5dd1db448a21)

**Comment by Kristanpivk123** [comment]
Hi, Marco,

I wish I could be of any use here but I'm afarid I can't be. For me a relatively reliable set-up vas to use two computers. I didn't really look into why that worked and why running both from one computer didn't. The only discovery that I made was that npcap was the problem and any additional instabilities I gust assigned to Windows being Windows. But I also think that you could just try using an additional laptop and see if that works (to have both python instances and Ethernet connections totally separated; that was also a suggestion I found here on Github somewhere) since in the application you probably won't have both (or maybe you will; in that case good luck). 
In my case the PC also broadcasted the information so I guess having both WHITE beets on the same physical Ethernet could confuse them (just guessing, not really that much on an IT guy).

Hope you figure it out,
Kristan

**Comment by Kristanpivk123** [comment]
I wrote "Relatively reliable" because on PC it didn't work as good as on laptop and it wasn't really "9/10" times but more that it worked for a few hours and at some point it stopped working correctly (I think that there were timeouts at some point, but I,m not sure where), but that happened when I was using a PC, which was connected to the WHITE beet through a switch. The solution then was to either use a laptop (if I had it at that time) or to use a ETH-USB adapter instead of ETH connection on my PC and connect directly to the WHITE beet. Out of all of that trial and error I can say that running this Python script on Windows is not very reliable, but it was enough for me.

I would really appreciate that so I'm gonna hold you to that if I have any (I'm still figuring out all of the problems with getting some current out of different EVSEs) :)

Best regards,
Kristan
