### ISSUE TITLE
Question: Getting intermittent messages on EV Side while testing EVSE side board

### ISSUE THREAD

**Issue by pranavsparalikar-eaton** [Sevenstax/FreeV2G#264]
Setup
Platform: PEV (WB-CARRIER-BOARD-PI-1.1)
Firmware Version: i.e. V01_00_07
Host Controller Interface: Ethernet
Host: FreeV2G

Platform: EVSE (Customized - own HW design)
Firmware Version: i.e. V02_01_00
Host Controller Interface: SPI
Host: Own Implementation

Description:
I have successfully tested a complete charging sequence using EV and EVSE CODICO Eval boards by running EV side python script in the past. 
Now I am able to test the same using own designed PLC board with an EVSE side WB module (and the same EV side CODICO Eval Board and the python script) successfully.
![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/4f6cf9b4-73e4-49f8-88e5-370c61f2dfff)

One point (while testing with customized Board for EVSE) is, as captured in screenshots below, we are getting some intermittent messages in between the expected messages on the EV side WB module serial terminal:
![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/a7593565-d479-431f-b69b-25bfc921bce0)

![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/7e815d90-7a0b-4751-83ec-18d4864cd473)

I would like to know about these messages and why are they appearing now..? Do these indicate any errors or warning..? 

These messages were not seen with the EVSE side WB module connected to the EV side WB module (both Eval Boards).

Request you to have a look and suggest a way ahead.

--
Thanks & Regards,
Pranav

**Comment by lho-stx** [comment]
Hey @pranavsparalikar-eaton,
the messages indicate an unstable PWM duty cycle. Most likely the new hardware has a duty cycle that has more tolerance then the Whitebeet PWM generator. Another possibility is, that the new hardware has the duty cycle set to a boundary where the Whitebeet applies rounding to the income PWM duty cycle.  The duty cycle has a quite big valid value range (3% upto 7%), in your log the duty cycle jumps between 5.6% and 5.7%. So this is nothing to worry about.

If you want, you can inspect the duty cycle of the control pilot with an oscilloscope when using your new hardware, but as long there is no problem with the charging session, I do not seen any reason for immediate action.

Best regards,
lho
