### ISSUE TITLE
Cocido board is not communicating with the target

### ISSUE THREAD

**Issue by Livante** [Sevenstax/FreeV2G#267]
Hello! 

We have a communication issue with the FreeV2G tool. Followed all the instructions from the README and 
We followed every step described in the README from the tool.

 

First we open the FreeV2G tool and run the command with the correct MAC Address:
![1](https://github.com/Sevenstax/FreeV2G/assets/48677088/0df11cbf-8e70-46ee-85b7-2f60951bf125)

After this we connect the CP and PE to the Codico board:

We load the QCA firmware on the target, run all the necessary commands and start the slac procedure on the target with the Diagnostic tool but nothing new comes up in the open, and running terminal:

![2](https://github.com/Sevenstax/FreeV2G/assets/48677088/c64914a0-0853-4cc5-84ee-e95ac4e07aa2)

We also try to read other values that can be read only after the slac matching was successful 
but nothing happens.

Please provide us support as soon as possible. We would like to schedule a meeting with you.
[wireshark log.txt](https://github.com/Sevenstax/FreeV2G/files/13660117/wireshark.log.txt)

**Comment by lho-stx** [comment]
Hey @Livante,

it seems the Whitebeet does not see any state changes on the control pilot. Does your other device support state handling accordingly to IEC61851-1? FreeV2G waits for the State B on the control pilot line before starting SLAC and V2G. You are free to modify FreeV2G so it does not wait until State B is detected on the control pilot line and starts SLAC matching immediately.

Unfortunately we do not discuss direct customer support in this issue tracker. Please contact Codico if you need more support with the Whitebeet. They will help you getting the support you need.

With best regards,
lho
