### ISSUE TITLE
Question: How can I stop the charging?

### ISSUE THREAD

**Issue by alabora33** [Sevenstax/FreeV2G#271]
Hi,
From the EVSE side perspective, what should I do to stop the charging process with a command or condition?
Could you please explain the steps required to stop charging and the functions to be used?

**Comment by lho-stx** [comment]
Hey @alabora33,

to stop the charging from EVSE side you need to send a notification to the PEV with a request to stop the charging process. The message you need is "Send notification" (`18.10.20 Send Notification` in the Whitebeet manual). You need to set the notification code to "StopCharging" (Renegotiation needs to be false) and the timeout to a sane timeout value. According to ISO15118-2 the PEV shall stop the charging within the timeout. If the PEV fails to stop the charging within the timeout you may stop it by turning-off control pilot or opening the mains contactors.

This also applies to #272 and #249.

Best regards,
lho
