### ISSUE TITLE
Question:How can stop the charge properly

### ISSUE THREAD

**Issue by alperenyilmaz99** [Sevenstax/FreeV2G#272]
When I try to stop in Evse.py the charging in this way,:
```
            if stopvariable =="stop":
                self._handleRequestStopCharging(b'\x00\x00\x06\x05\x00')
                self._handleWeldingDetectionStarted(b'')
                self._handleSessionStopped(b'\x00')
                break
self.whitebeet.v2gEvseStopListen()
```
I receive this error:
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> stop
----------------ID--------------------------------- None
-----------------------DATA-------------------------- None
"Request Stop Charging" received
Timeout: 1541
Timeout: no
-------------STOP-----------------------------
***********************************Relay Off:  0
Warning: Module did not accept command 27:6f, return code: 17
"Welding Detection Started" received
"Session stopped" received
Closure type: 0
-------------STOP-----------------------------
***********************************Relay Off:  0
EVSE loop finished

What is the correct way to stop the charging without encountering an error?"

**Comment by lho-stx** [comment]
Please refer to #271
