### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Livante** [Sevenstax/FreeV2G#275]
Hello,

We are trying to start the slac between codico a development board that has the SLAC protocol implemented.
we can see that, after a start request from a diagnostic tool, the start function from slac is reached(Breakpoint is hit), but the protocol is hanging somewhere. 
 
we have set the correct MAC address like below:
![8b516b46-440b-4300-8a77-5d90dd80989e](https://github.com/Sevenstax/FreeV2G/assets/48677088/d9b85fc9-f02a-45f7-8c00-de2ed1b400d3)

With the diagnostic tool with we are using we tried to set the MAC address for the development Board in 3 different manners:

1.  Random MAC Address
2. MAC Address which is present in the picture from the terminal
3. MAC Address which is present in the picture from the terminal + 2 (Whitebeet MAC Addr)

We changed the one of your Python script as we saw that for the connection we need to have 8V on the CP+PE, but when we measured them we only had 0.43V, so now the Voltage check is ignored 
![pythonCP](https://github.com/Sevenstax/FreeV2G/assets/48677088/bd68647a-0e25-4b96-93d4-07faf7528e3d)
![PythonCP2](https://github.com/Sevenstax/FreeV2G/assets/48677088/2306d036-bb81-40f3-9443-c194527c4e4f)

We also used Putty to see all the transmitted messages and we see that PARM.CNF is missing. I also attach here the log file:
[puttylog.txt](https://github.com/Sevenstax/FreeV2G/files/13887090/puttylog.txt)

**Comment by lho-stx** [comment]
Hey @Livante,

thank you for detailed information, but to investigate this issue further we need more information/log files. Can you please create a new issue and use the "Bug report" template? Please make sure to provide all the requested information in the issue template. You can find information about how to create log files in the wiki, the necessary chapters are named in the issue template. If you have problems creating the log files, please let me know!

Thank you!
lho
