### ISSUE TITLE
Issues installing software on HP laptop running Ubuntu

### ISSUE THREAD

**Issue by nealEVB** [Sevenstax/FreeV2G#282]
**Your Setup**
Platform:  EVSE
Firmware Version: i.e. V01_00_05
Host Controller Interface: Ethernet 
Host: FreeV2G (EV_v1.0.4_0) / Own Implementation

on HP laptop we tried to install on windows with errors.  Then we installed Ubuntu on the laptop and tried the 
install again

**Describe the bug**
The install is failing with similar error msg as when we tried on windows.

Please see logs to follow the steps.

**Logs**

﻿
evbuddy@evbuddy-HP-ProBook-640-G2:~/FreeV2G$ pyton3 -m venv .venv
Command 'pyton3' not found, did you mean:
  command 'python3' from deb python3 (3.11.4-5)
Try: sudo apt install <deb name>
evbuddy@evbuddy-HP-ProBook-640-G2:~/FreeV2G$ python3 -m venv .venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.11-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/evbuddy/FreeV2G/.venv/bin/python3

evbuddy@evbuddy-HP-ProBook-640-G2:~/FreeV2G$ apt install python3.11 -venv
apt 2.7.3 (amd64)
E: Command line option 'e' [from -venv] is not understood in combination with the other options.
evbuddy@evbuddy-HP-ProBook-640-G2:~/FreeV2G$ apt install python3.11-venv
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
evbuddy@evbuddy-HP-ProBook-640-G2:~/FreeV2G$ sudo su
root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# pwd
/home/evbuddy/FreeV2G
root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# python3 -m venv .venv
root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# source .venv/bin/activate
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# pip install --pre scapy[basic]
Collecting scapy[basic]
  Downloading scapy-2.5.0.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 3.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ipython (from scapy[basic])
  Obtaining dependency information for ipython from https://files.pythonhosted.org/packages/db/04/1bf767de3ee9e462a09efb1eab3074d715ef5ab582b8a0cb6d5d5615212d/ipython-8.20.0-py3-none-any.whl.metadata
  Downloading ipython-8.20.0-py3-none-any.whl.metadata (5.9 kB)
Collecting decorator (from ipython->scapy[basic])
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython->scapy[basic])
  Obtaining dependency information for jedi>=0.16 from https://files.pythonhosted.org/packages/20/9f/bc63f0f0737ad7a60800bfd472a4836661adae21f9c2535f3957b1e54ceb/jedi-0.19.1-py2.py3-none-any.whl.metadata
  Downloading jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting matplotlib-inline (from ipython->scapy[basic])
  Downloading matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.41 (from ipython->scapy[basic])
  Obtaining dependency information for prompt-toolkit<3.1.0,>=3.0.41 from https://files.pythonhosted.org/packages/ee/fd/ca7bf3869e7caa7a037e23078539467b433a4e01eebd93f77180ab927766/prompt_toolkit-3.0.43-py3-none-any.whl.metadata
  Downloading prompt_toolkit-3.0.43-py3-none-any.whl.metadata (6.5 kB)
Collecting pygments>=2.4.0 (from ipython->scapy[basic])
  Obtaining dependency information for pygments>=2.4.0 from https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl.metadata
  Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting stack-data (from ipython->scapy[basic])
  Obtaining dependency information for stack-data from https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl.metadata
  Downloading stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting traitlets>=5 (from ipython->scapy[basic])
  Obtaining dependency information for traitlets>=5 from https://files.pythonhosted.org/packages/45/34/5dc77fdc7bb4bd198317eea5679edf9cc0a186438b5b19dbb9062fb0f4d5/traitlets-5.14.1-py3-none-any.whl.metadata
  Downloading traitlets-5.14.1-py3-none-any.whl.metadata (10 kB)
Collecting pexpect>4.3 (from ipython->scapy[basic])
  Obtaining dependency information for pexpect>4.3 from https://files.pythonhosted.org/packages/9e/c3/059298687310d527a58bb01f3b1965787ee3b40dce76752eda8b44e9a2c5/pexpect-4.9.0-py2.py3-none-any.whl.metadata
  Downloading pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython->scapy[basic])
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 8.9 MB/s eta 0:00:00
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython->scapy[basic])
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth (from prompt-toolkit<3.1.0,>=3.0.41->ipython->scapy[basic])
  Obtaining dependency information for wcwidth from https://files.pythonhosted.org/packages/fd/84/fd2ba7aafacbad3c4201d395674fc6348826569da3c0937e75505ead3528/wcwidth-0.2.13-py2.py3-none-any.whl.metadata
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Collecting executing>=1.2.0 (from stack-data->ipython->scapy[basic])
  Obtaining dependency information for executing>=1.2.0 from https://files.pythonhosted.org/packages/80/03/6ea8b1b2a5ab40a7a60dc464d3daa7aa546e0a74d74a9f8ff551ea7905db/executing-2.0.1-py2.py3-none-any.whl.metadata
  Downloading executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython->scapy[basic])
  Obtaining dependency information for asttokens>=2.1.0 from https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2.4.1-py2.py3-none-any.whl.metadata
  Downloading asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython->scapy[basic])
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting six>=1.12.0 (from asttokens>=2.1.0->stack-data->ipython->scapy[basic])
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading ipython-8.20.0-py3-none-any.whl (809 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 809.2/809.2 kB 5.0 MB/s eta 0:00:00
Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.1 MB/s eta 0:00:00
Downloading pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 5.8 MB/s eta 0:00:00
Downloading prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.1/386.1 kB 7.2 MB/s eta 0:00:00
Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.1 MB/s eta 0:00:00
Downloading traitlets-5.14.1-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 kB 8.4 MB/s eta 0:00:00
Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Building wheels for collected packages: scapy
  Building wheel for scapy (pyproject.toml) ... done
  Created wheel for scapy: filename=scapy-2.5.0-py2.py3-none-any.whl size=1444328 sha256=5f6cb858fc91209c2b737ebbded89b0ce6c6ab881f79e659b254304aea44e82e
  Stored in directory: /root/.cache/pip/wheels/11/ff/28/a1348d0c6d006242c053521732bc2951d0c9eca62a11430da1
Successfully built scapy
Installing collected packages: wcwidth, pure-eval, ptyprocess, traitlets, six, scapy, pygments, prompt-toolkit, pexpect, parso, executing, decorator, matplotlib-inline, jedi, asttokens, stack-data, ipython
Successfully installed asttokens-2.4.1 decorator-5.1.1 executing-2.0.1 ipython-8.20.0 jedi-0.19.1 matplotlib-inline-0.1.6 parso-0.8.3 pexpect-4.9.0 prompt-toolkit-3.0.43 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.17.2 scapy-2.5.0 six-1.16.0 stack-data-0.6.3 traitlets-5.14.1 wcwidth-0.2.13
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# pip install Cython
Collecting Cython
  Obtaining dependency information for Cython from https://files.pythonhosted.org/packages/26/2c/6a887c957aa53e44f928119dea628a5dfacc8e875424034f5fecac9daba4/Cython-3.0.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading Cython-3.0.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Downloading Cython-3.0.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 4.8 MB/s eta 0:00:00
Installing collected packages: Cython
Successfully installed Cython-3.0.8
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# pip install python-libpcap
Collecting python-libpcap
  Downloading python-libpcap-0.4.2.tar.gz (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Cython>=0.29.23 in ./.venv/lib/python3.11/site-packages (from python-libpcap) (3.0.8)
Building wheels for collected packages: python-libpcap
  Building wheel for python-libpcap (pyproject.toml) ... error
  error: subprocess-exited-with-error
 
  × Building wheel for python-libpcap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      /tmp/pip-build-env-twkqmhpd/overlay/lib/python3.11/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
     
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
     
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
     
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
     
      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/exception.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/open.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/pcap.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/utils.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/cli.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/__main__.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/parse.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      copying pylibpcap/__init__.py -> build/lib.linux-x86_64-cpython-311/pylibpcap
      running egg_info
      writing python_libpcap.egg-info/PKG-INFO
      writing dependency_links to python_libpcap.egg-info/dependency_links.txt
      writing entry points to python_libpcap.egg-info/entry_points.txt
      writing requirements to python_libpcap.egg-info/requires.txt
      writing top-level names to python_libpcap.egg-info/top_level.txt
      reading manifest file 'python_libpcap.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.h' under directory 'src'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file 'python_libpcap.egg-info/SOURCES.txt'
      copying pylibpcap/base.c -> build/lib.linux-x86_64-cpython-311/pylibpcap
      running build_ext
      building 'pylibpcap.base' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/pylibpcap
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -g -fwrapv -O2 -fPIC -I/home/evbuddy/FreeV2G/.venv/include -I/usr/include/python3.11 -c pylibpcap/base.c -o build/temp.linux-x86_64-cpython-311/pylibpcap/base.o -lpcap
      error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-libpcap
Failed to build python-libpcap
ERROR: Could not build wheels for python-libpcap, which is required to install pyproject.toml-based projects
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# ip list
Object "list" is unknown, try "ip help".
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# ip list
Object "list" is unknown, try "ip help".
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# sudo .venv/bin/python3 Application.py eth - i eth0 -m c4:93:00:34:ab:05 -r EVSE
usage: Application.py [-h] -i INTERFACE [-m MAC] -r {EVSE,EV} [-c [CONFIG]] [-p] {eth,spi}
Application.py: error: the following arguments are required: -i/--interface
(.venv) root@evbuddy-HP-ProBook-640-G2:/home/evbuddy/FreeV2G# sudo .venv/bin/python3 Application.py eth -i eth0 -m c4:93:00:34:ab:05 -r EVSE
Welcome to Codico Whitebeet EVSE reference implementation
Initiating framing interface
Traceback (most recent call last):
  File "/home/evbuddy/FreeV2G/Whitebeet.py", line 106, in __init__
    self.framing.initialize_framing(iftype, iface, mac)
  File "/home/evbuddy/FreeV2G/FramingInterface.py", line 54, in initialize_framing
    import EthernetAdapter
  File "/home/evbuddy/FreeV2G/EthernetAdapter.py", line 12, in <module>
    from pylibpcap.base import Sniff
ModuleNotFoundError: No module named 'pylibpcap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/evbuddy/FreeV2G/Application.py", line 52, in <module>
    with Evse(args.interface_type, args.interface, args.mac) as evse:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evbuddy/FreeV2G/Evse.py", line 8, in __init__
    self.whitebeet = Whitebeet(iftype, iface, mac)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evbuddy/FreeV2G/Whitebeet.py", line 120, in __init__
    raise ConnectionError("Failed to initialize the framing interface on \"{}\"".format(self.framing.sut_interface))
ConnectionError: Failed to initialize the framing interface on ""

**Comment by lho-stx** [comment]
Hey @nealEVB,

do you have `libpcap-dev` installed on your host machine? I not please install it and try setting up FreeV2G again.

Best regards,
lho
