### ISSUE TITLE
Question: Message performance Timeout reached

### ISSUE THREAD

**Issue by pranavsparalikar-eaton** [Sevenstax/FreeV2G#284]
EV Setup:
An EV Simulator

EVSE Setup:
Platform: EVSE (WB-CARRIER-BOARD-EI-1.1)
Firmware version: V02_01_00
Host Controller Interface: SPI
Host: Own HW

I am trying to complete a whole charging cycle with Codico WB EVSE Module and an EV Simulator. All the required steps, viz. cable check, precharge, actual charging (with 400V, 7A) are executed properly. But the charging cycle is terminated abruptly with an error "Message performance Timeout of 4550 ms reached". Pls. refer the screenshot of the serial log below:
![Stop Charging](https://github.com/Sevenstax/FreeV2G/assets/136327877/0fab9b8f-fd58-4443-ba9b-70949504d04f)

Could you pls. let me know all the possible reasons of this error..? Pls. let me know if any additional info. is required from myside.

Awaiting for your reply.

Pls. note.: I have tested the EV Simulator separately and found to be working well the DIN as well as ISO.

--
Thanks & Regards,
Pranav

**Comment by lho-stx** [comment]
Hey @pranavsparalikar-eaton,

please use the other issue template for such kind of issues:

https://github.com/Sevenstax/FreeV2G/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Please create a new issue and add the information that is asked for in the issue template. There are multiple reasons why  charging can fail, to really tell you anything about it we need the log files.

Thank you and best regards,
lho

**Comment by pranavsparalikar-eaton** [comment]
Hi @lho-stx ,

Thanks for your reply. Actually, there was some sync issue in my FW due to which, the the stop charging command (0x6F) was sent before the status message Stop Charging Requested by the EV.

![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/abf40aef-37b8-419f-9370-e94846e42cd8)


I realized it and then fixed it. Now everything is working well.

![image](https://github.com/Sevenstax/FreeV2G/assets/136327877/8553caaf-a600-4ad5-b157-155499e3ceeb)


Thank you for your support.

--
Best Regards,
Pranav
