### ISSUE TITLE
I get an error running 

### ISSUE THREAD

**Issue by nealEVB** [Sevenstax/FreeV2G#287]
I type command
with EVSE board connected, after successful activation I type
sudo .venv/bin/python Application.py eth -i eth0 -m C4:93:00:34:D3:1F -r EVSE 

I get errors here are screenshots of error output.  This is not the complete output, but Im
not sure how to capture the entire output

![IMG_3556](https://github.com/Sevenstax/FreeV2G/assets/132850252/e963a8ef-3580-45f8-a940-d5d5fb314553)
![IMG_3555](https://github.com/Sevenstax/FreeV2G/assets/132850252/c8ab2973-1cc7-4e7f-a078-aea15171a0c1)

**Comment by lho-stx** [comment]
Hey @nealEVB,

please create a new issue and provide all logs accordingly to your setup:

https://github.com/Sevenstax/FreeV2G/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Also make sure to have a look into the [get started wiki entry](https://github.com/Sevenstax/FreeV2G/wiki/guide-quick-start).

Best regards,
lho
