### ISSUE TITLE
Looking for a collaborator who has a working version of White Beet ESVE system

### ISSUE THREAD

**Issue by Hipowerguy** [Sevenstax/FreeV2G#298]
I am designing an ESVE and am looking for a collaborator who has a real working version of White Beet ESVE system.  Not just the demo.  Something with all the proper exceptions handling.

I can provide the power electronic knowhow in exchange.  I have designed industrial power converters producing hundreds of kW to many MW.

Anybody looking for a win/win?

**Comment by lho-stx** [comment]
Hey @Hipowerguy,

please send an e-Mail with your contact data to info@sevenstax.de. We would like to discuss this topic with you.

Please put "Whitebeet Collaboration" in the subject.

Thank you and best regards,
lho
