### ISSUE TITLE
Doku: WhiteBeet User Manual rev. 2.2

### ISSUE THREAD

**Issue by klth** [Sevenstax/FreeV2G#3]
**In 9.1.3**
Hier wird angegeben: 
> „When sending messages not related to any particular request by the host controller, the WHITE beet –module will set the Request ID to 0xFF.“

Stimmt allerdings nicht für das V2G Module dort ist der Broadcast 0x00.

**In 10.3.1**
![grafik](https://user-images.githubusercontent.com/47042689/125458327-f1393627-edec-4537-a741-54ce67236f7e.png)
Aufbau undeutlich, es müsste sein:

> Code uint8
> String Len uint8
> Version string

Dies betrifft auch 10.3.2, 10.3.5 etc. alle wo eine String Variable definiert ist.

**In 15.10.1 und 15.10.2**
Example: Hex Wert für „2 protocols“ falsch. 0 -> 2

**In 15.1.**
Eventuell Type boolean hinzufügen und dass es sich um uint8 mit 1 = true und 0 = false handelt.

Bei Type exponential hinzufügen das der Exponent nicht kleiner als -3 sein darf. Zum Beispiel bei DiscoverChargeParameters->PeakCurrentRipple von 20000 * 10^-4, was laut Definition gültig sein müsste, bricht der Ladevorgang ab. Hoch -3 geht

**In 15.12.10**
Die Boolean Variable ob die nachfolgende Info existiert fehlt.
![grafik](https://user-images.githubusercontent.com/47042689/125457860-53c4ee17-4fb7-41ef-a419-dc4748045fa9.png)
![grafik](https://user-images.githubusercontent.com/47042689/125458154-1a139c0f-566d-497d-a0ec-f91748a14350.png)

**Comment by jpo-stx** [comment]
Hi @klth,

thank you for detailed input. Here my comments:

> Stimmt allerdings nicht für das V2G Module dort ist der Broadcast 0x00.

The broadcast should always be 0xFF. If it's off in the V2G module we need to fix this.

> Dies betrifft auch 10.3.2, 10.3.5 etc. alle wo eine String Variable definiert ist.

Generally we need to define the type string. Strings with a variable length are always prefixed with the length.

> In 15.10.1 und 15.10.2
> Example: Hex Wert für „2 protocols“ falsch. 0 -> 2

Thanks for the hint!

> In 15.1.
> Eventuell Type boolean hinzufügen und dass es sich um uint8 mit 1 = true und 0 = false handelt.

As with the string type we need a chapter describing the "standard" types.

> Bei Type exponential hinzufügen das der Exponent nicht kleiner als -3 sein darf. Zum Beispiel bei DiscoverChargeParameters->PeakCurrentRipple von 20000 * 10^-4, was laut Definition gültig sein müsste, bricht der Ladevorgang ab. Hoch -3 geht

You are correct, the range of the exponent needs to be specified. It is -3 to 3.

> In 15.12.10
> Die Boolean Variable ob die nachfolgende Info existiert fehlt.

Correct

BR
Jan

**Comment by jpo-stx** [comment]
The issues should be solved with the latest Whitebeet firmware version V01_01_03 and the latest user manual v2.8.
