### ISSUE TITLE
Question: WB PS 1.1 Module: Ethernet connection without Phy possible?

### ISSUE THREAD

**Issue by andrelmk** [Sevenstax/FreeV2G#307]
On my custom board I have an RMII connection between my microcontroller an WB PS 1.1 Module.
From the log I can see that the WB is set correctly set to Eth. mode. I am sending Eth. packets from my controller with the correct MAC destination address, but the WB module does not respond.
On the MDC/MDIO lines I can see that the WB is constantly trying to communicate with the Phy? Could the issue be related to a missing Phy? Since I have adirect connection between microcontroller and WB, I have no Phy on the board.
What does the WB Ethernet initialization routine do, when a Phy cannot be found?

What other reasons could there be, why the WB does not respond to Eth. packets?

Thanks.

**Comment by lho-stx** [comment]
Hey @andrelmk,

I would like to refer you to Codico, because this sound more like a hardware related issue. If they tell you everything is fine with your PCB design, please feel free to reopen the issue.

Best regards,
lho
