### ISSUE TITLE
Session Stops after "Set EVSE ID" when Hyundai Kona is connected

### ISSUE THREAD

**Issue by nikhilnezodi** [Sevenstax/FreeV2G#31]
Hello All,
I have been working on the WB-CARRIER-BOARD-EI ISO 15118(EVSE) module for a while. The vehicle I tested on is Hyundai Kona. On running the Application.py file and observing the logs the session stops after "SET EVSE ID". The format is "0" so I set the EVSE ID in "+49*XXX*XXX*XXX" format as mentioned in the Sevenstax Usermanual. 
This seemed similar to issue #16 so I tried by changing Energy Transfer modes. I also tried to set EVSE ID as 0 which also did not help in the process. I had not faced any such issues while testing with Tata Nexon.

Firmware version used: Sevenstax_WHITEBEET_ISO15118_EVSE_EIM_V01_01_06
Code used is the latest FreeV2G code

I have attached screenshots for the log observations - 
1. Initial Log
![Initial](https://user-images.githubusercontent.com/63468012/150282225-d2ea0f55-7ddf-424d-b2a0-3148f9bcbc27.png)
 
2. When EVSE ID was set to "0"
![EVSE_ID_0](https://user-images.githubusercontent.com/63468012/150282222-a2496f86-07db-48f5-8cc9-c548a5e4c92f.png)

3. When Energy Transfer Mode was set to "1"
![Mode_1](https://user-images.githubusercontent.com/63468012/150282229-999e983c-3e9f-490e-a773-abb0c6cadcfa.png)

4. When Transfer modes were set as [0,1,2,3]
![Modes_0_1_2_3](https://user-images.githubusercontent.com/63468012/150282231-d119b632-ca61-43a8-a565-e2119470d494.png)

**Comment by jpo-stx** [comment]
@nikhilnezodi , it seems a bit strange that the session id is all zeros. Can you activate the port mirror and do a wireshark log of the ethernet interface? See Whitebeet User Manual chapter 12.3.10.

**Comment by nikhilnezodi** [comment]
@jpo-stx I have attached the screenshot of the latest logs. 
![updated log](https://user-images.githubusercontent.com/63468012/151101802-7f633ac8-e439-4484-a117-5076ae3f26c3.png)

Also activated the port mirror and attached the wireshark logs obtained.
[Hyundai_Kona_wireshark_logs.zip](https://github.com/Sevenstax/FreeV2G/files/7938823/Hyundai_Kona_wireshark_logs.zip)

**Comment by jpo-stx** [comment]
Hi @nikhilnezodi , are you sure that you activated the port mirror? How is your setup, are you connected directly to the Whitebeet or do you have a switch in between?
The EV wants to charge with the DIN protocol, there is an issue when the energy transfer modes are not set correctly. Please check my comment in https://github.com/Sevenstax/FreeV2G/issues/16#issuecomment-988695769 and chapter **17.10.7 Set energy transfer modes** in the manual and verify that you have set the modes correctly.

**Comment by nikhilnezodi** [comment]
@jpo-stx Thanks. Setting the Energy transfer mode to 1 (DC Extended) worked for me.
