### ISSUE TITLE
Question: Wireshark doesn't show bridged EV messages

### ISSUE THREAD

**Issue by Zaghz** [Sevenstax/FreeV2G#310]
I am using WSL on Windows 11 with an External virtual switch on my eth interface.

Wireshark normally shows me messages sent by the EV board (not whitebeet). However, when I run the Application script the messages stop showing up from the EV and only messages that are exchanged between the WHITEBEET acting as EVSE and the Host are shown.

![image](https://github.com/Sevenstax/FreeV2G/assets/48098749/f2823670-8dc9-4c01-8d4f-e669aba32d50)

**Comment by jpo-stx** [comment]
Do you use the port mirror function of the Whitebeet?

**Comment by nststx** [comment]
Hi @Zaghz,

Thanks for posting your question. Unfortunately you didn't use the provided template for creating your issue. To keep up with our issue tracker we only accept issues following our templates. Please refer to [this guide](https://github.com/Sevenstax/FreeV2G/issues/304) on how to post your issue or question.

If your issue still persists please open a new one using our provided template.

Best regards and thanks for  your understanding and patience,
Niklas Stoffers
