### ISSUE TITLE
Question: How can I set the IPV6 address on the EVSE board.

### ISSUE THREAD

**Issue by Rajdipsinh15** [Sevenstax/FreeV2G#325]
**Before you post**
- [x] I confirm that I've read the [guide on how to post issues](https://github.com/Sevenstax/FreeV2G/issues/304)
- [x] I confirm that I've consulted the [wiki](https://github.com/Sevenstax/FreeV2G/wiki) about my issue

**My Question**
Hi, I want to the set the IPV6 address of my EVSE ISO15118 board. I go through the User-Manual of the whitebeet and in that I can see that they already give the command of the Set IPV6 address but when I run the setup and see the logs I can not that it set any IPV6 address.
So can you please explain me regarding the IPV6 in brief. 
I also have one more question that right now I am trying the connect my MCU with the EVSE ISO15118 over Ethernet IPV6. So can I connect them over IPV6?

**Comment by lho-stx** [comment]
Hey @Rajdipsinh15,

I am not quite sure if I understood your question.

Are you talking about the host controller interface? You can connect to the WHITE Beet with framing protocol via SPI/ETH only, the host controller interface does not support framing over TCP. When using ETH you need to use the MAC of the WHITE Beet for communication.

If you are talking about the IPv6 addres of the V2G communication, it is broadcasted after SLAC was successful and the WHITE Beet joined a HPGP network. Please also check #293 and tell me if the information in this issue answers your questions.

Best regards,
lho

**Comment by Rajdipsinh15** [comment]
Hi @lho-stx ,
 
Thanks for quick reply.
 
I understood that the host controller interface does not support framing over TCP. and also understood that when using ETH we need to use the MAC of the white beet for communication.
 
Now I first tells you about my setup.
 
I have one EVSE ISO15118 board. and I have one MCU of IMXRT1064.
I connected both the board using the Ethernet cable.
Now I want to send the frames from the MCU IMXRT1064 to EVSE board. Now when I search for it that how to send the frames via Ethernet but for that I need the IP of the EVSE board. And for that when I see the User-Manual and in that they mention regarding the SET the IPV6 address. And for that I want to know how can I set the IPV6 Address.
 
So first tell me EVSE has the IPV6 or not? 
If not then how can I set the IPV6 for EVSE?
One more question for again clarification that can I send frame over ETHERNET IPV6 from MCU IMXRT1064 to EVSE board?

Thanks.

**Comment by Rajdipsinh15** [comment]
Hey   @lho-stx 
Can you please give me update on above issue.

Thanks.

**Comment by lho-stx** [comment]
Hey @Rajdipsinh15,

I am sorry, but I am still unsure what you want to do.

Sending any message to the WHITE Beet is only supported using the host interface (SPI or ETH) and Framing. You can not communicate with the WHITE Beet via IPv6 over the host interface. The WHITE Beet uses IPv6 for the V2G communication and you can only set the IPv6 address of the V2G application in the WHITE Beet (detailed information are in the user manual).

The WHITE Beet might forward IP packets seen at it's host controller interface to the PLC network, but this is not an official feature.

Best regards,
lho

**Comment by Rajdipsinh15** [comment]
Hey @lho-stx 

I have an EVSE ISO15118 board and an MCU of IMXRT1064. I connected both the board and the MCU using an Ethernet cable.

Now, I want to send frames from the MCU (IMXRT1064) to the EVSE board.

Can I send and receive frames using Ethernet IPv6 between the MCU (IMXRT1064) and the EVSE board?

Thanks.

**Comment by lho-stx** [comment]
Hey @Rajdipsinh15,

please apologize if I was unclear. I attached a diagram to better visualize the connections of the WHITE Beet.

![WHITE-Beet-communication](https://github.com/Sevenstax/FreeV2G/assets/103272216/6f6a5eeb-e1c7-4da1-832f-5a899135c8cb)

As you see, you can not communicate with the WHITE Beet from your host via IPv6/TCP, only via Framing protocol (using ether type 0x6003). IPv6/TCP is used for V2G communication (between WHITE Beet and PEV) only (using the PLC network). You can only set the IPv6 address of the WHITE Beet in the PLC network (for V2G communication).

Optional you can enable the port mirror, that is forwarding the IPv6/TCP traffic from the PLC network via WHITE Beet to your host (using the ethernet host controller interface). Although sending IPv6/TCP messages from the host into the PLC network might work, it is not officially supported and the WHITE Beet is still not IPv6 addressable from the host (it only forwards the packets into the PLC network).

I hope this answers your questions,
lho

**Comment by Rajdipsinh15** [comment]
Hi @lho-stx 

Thanks for the prompt reply and the solution.

Thanks
Rajdipsinh
