### ISSUE TITLE
Session stop after SDP response

### ISSUE THREAD

**Issue by vsCodeGB** [Sevenstax/FreeV2G#328]
**Your Setup**
Platform: EVSE
Firmware Version: V02_01_00
Host Controller Interface: SPI
Host: Own Implementation

**Describe the bug**
Session stops after SDP response. EV sends TCP [SYN] request to SECC port and get "Destination Unreachable".
I have reached charging loop with another cars, but this one does not start.
I made a search before posting and not found similar issue.

**Expected behavior**
To complete handshake with SECC TCP port that is in SDP responce.

**Logs**
- UART log missing
-  Pcap log: https://mega.nz/file/MP8wlIzR#lrMIo74BlGPzZvu9l8-YjT_IX933NupzwAScOUGYdNY

**Comment by lho-stx** [comment]
Hey @vsCodeGB,

this issue is the same as in #291. It will be fixed in the next FW version.

Best regards.
lho
