### ISSUE TITLE
Is there a passive/listen-only mode on the WB module?

### ISSUE THREAD

**Issue by ecmhl** [Sevenstax/FreeV2G#34]
I have a WB-CARRIER-BOARD-EI and have successfully began charging an EV with it. I also have a WB-CARRIER-BOARD-PI. For further development and trouble shooting, I'm wondering if the I one WB module could be configured in a passive (listen-only) mode to act as sniffer of communication between existing EV-EVSE, where it does not send any messages or participate in slac negotiation, and it only acts as a bridge to pass through PLC communication? I'm aware of the port mirror mode. Can this mode be operated as described?

**Comment by ttu-stx** [comment]
Hi ecmhk, tracing a communication between EV and EVSE where you don't have access to a port mirror on one of these participants can not be achieved using White Beet. But there are solutions available. Feel free to contact su directly: info@sevenstax.de
BR
