### ISSUE TITLE
Code is Stuck at Session start request

### ISSUE THREAD

**Issue by Shekhar-devise** [Sevenstax/FreeV2G#38]
Hello,

I'm using the Gloquad PLC module to interface with the Whitebeet PEV module.
Also, we are interfacing the white beet module with an Ethernet interface.

When I have started the repository I got a response up to CP voltage.

Create a new charging session
ControlPilot duty cycle: 5.5
after this message, the white beet PEV module should send SessionStarted (C0) status and SessionSetupReq to EVSE.
But when we checked its response. we are unable to get it.
I am sending the results that we got after running the code.

Python code Output messages:-------------------------------------------------------------------
Initiating framing interface
iface: enp4s0, mac: C4:93:00:21:56:64
Ev configuration: {'mac': 'C4:93:00:21:56:64', 'ev': {'evid': 'C4:93:00:21:56:64', 'protocol_count': 2,
'protocols': [0, 1], 'payment_method_count': 1, 'payment_method': [0],
'energy_transfer_mode_count': 2, 'energy_transfer_mode': [0, 4]}, 'battery': {'timestep': 10000,
'capacity': 50000, 'level': 49000, 'full_soc': 100, 'bulk_soc': 80, 'max_current': 100, 'max_power':
12000, 'max_voltage': 300, 'target_current': 40, 'target_voltage': 200, 'target_voltage_delta': 10,
'max_current_AC': 0, 'max_voltage_AC': 0, 'min_current_AC': 0}}
Set the CP mode to EV
Start the CP service
Set SLAC to EV mode
Start SLAC
Wait until an EVSE connects
cp_dc = 5.5
EVSE connected
Start SLAC matching
SLAC matching successful
Set V2G mode to EV
Set V2G configuration
Set DC charging parameters
Set AC charging parameters
Start V2G
Change State to State C
controlPilotSetResistorValue res = 0
Create new charging session
ControlPilot duty cycle: 5.5

------------------------------------------------------------------------------------------------

White beet debug log

[  217.247] [NOTICE] SLAC: stxSLAC_Stop()
[  217.348] [WARN  ] V2GCPS: stxV2GCPS_Stop() - Failed
[  217.692] [NOTICE] V2GCPS: Changed Max Current EV State (7)
[  217.692] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[  217.869] [NOTICE] SLAC: stxSLAC_Start()
[  221.466] [NOTICE] V2GCPS: Changed Max Current EV State (1)
[  221.466] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[  221.467] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[  221.468] [NOTICE] V2GCPS: # V2GCPS_INFOTYPE_CP_DUTY_CYCLE
[  221.468] [NOTICE] V2GCPS: Duty cycle is 56 permill
[  226.755] [NOTICE] SLAC: stxSLAC_StartSlacMatchingProcess()
[  226.861] [WARN  ] SLAC: # SLAC_STATE_RECV_SLAC_PARAM_CNF - TIMEOUT
[  230.068] [NOTICE] Q7KCOM: PIB File was updated => Download PIB without reset
[  231.458] [NOTICE] Q7KCOM: PIB File was updated => Download PIB without reset
[  231.488] [NOTICE] APL-ETH: Got link:
[  231.488] [NOTICE] APL-ETH:     Interface: eth0
[  231.489] [NOTICE] APL-ETH:     MAC:       C4:93:00:21:56:65
[  231.490] [NOTICE] SLACSERV: # NC_SLAC_SUCCESS
[  231.514] [NOTICE] V2GCPS: Changed Max Current EV State (7)
[  231.514] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[  231.515] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[  231.516] [NOTICE] V2GCPS: # V2GCPS_INFOTYPE_CP_DUTY_CYCLE
[  231.516] [NOTICE] V2GCPS: Duty cycle is 1000 permill
[  232.122] [NOTICE] V2GSVC: Starting in EV mode.
[  233.389] [NOTICE] APL-MAIN: 
[  233.389] [NOTICE] APL-MAIN: =============================
[  233.390] [NOTICE] APL-MAIN: NEW LAN CONFIGURATION (IPv6): 
[  233.390] [NOTICE] APL-MAIN: for IP Config handle [fe00] 
[  233.391] [NOTICE] APL-MAIN: IPv6 Addresses:
[  233.392] [NOTICE] APL-MAIN:   Link-Local:  fe80:0:0:0 : c693:ff:fe21:5665
[  233.393] [NOTICE] APL-MAIN:   Local: 0:0:0:0 : 0:0:0:0
[  233.393] [NOTICE] APL-MAIN:   DNS1:  2001:4860:4860:0 : 0:0:0:8888
[  233.394] [NOTICE] APL-MAIN:   DNS2:  fd00:0:0:0 : be05:43ff:fe44:5280
[  233.395] [NOTICE] APL-MAIN: =============================
[  233.396] [NOTICE] APL-MAIN: 
[  241.397] [WARN  ] APL-ETH: # Unhandled Ethernet notifycode 365
[  247.356] [NOTICE] Q7K: =========================================
[  247.356] [NOTICE] Q7K:   CPU ON RECEIVED
[  247.357] [NOTICE] Q7K: =========================================
[  247.358] [NOTICE] Q7K: QCA7K_SPI_REG_SIGNATURE = 0xAA55
[  247.359] [NOTICE] Q7K: =========================================
[  247.360] [NOTICE] Q7K:   QCA700x is READY
[  247.360] [NOTICE] Q7K: =========================================
[  248.885] [NOTICE] Q7KCOM:  ======================================= 
[  248.885] [NOTICE] Q7KCOM:    FW and PIB was loaded successful 
[  249.327] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.328] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.329] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.330] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.331] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.332] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.333] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.334] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.335] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.336] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.337] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.338] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.339] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.340] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.341] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.342] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.344] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.345] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.346] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.347] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.348] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.349] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.350] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.351] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.352] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.353] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.354] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.355] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.356] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.357] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.358] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.359] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.360] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.361] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.362] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.363] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.364] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.365] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.367] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.368] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.369] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.370] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.371] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.372] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.373] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.374] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.375] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.376] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.377] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.378] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.379] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.380] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.381] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.382] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.383] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.384] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.385] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.386] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.387] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.389] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.390] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.391] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.392] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.393] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.394] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.395] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.396] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.397] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.398] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.399] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.400] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.401] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.402] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.403] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.404] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.405] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.406] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.407] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.408] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.409] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.411] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.412] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.413] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.414] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.415] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.416] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.417] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.418] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.419] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.420] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.421] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.422] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.423] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.424] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.425] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.426] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.427] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.428] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.429] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.430] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.431] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.432] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.434] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.435] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.436] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.437] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.438] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.439] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.440] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.441] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.442] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.443] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.444] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.445] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.446] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.447] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.448] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.449] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.450] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.451] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.452] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.453] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.454] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.456] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.457] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.458] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.459] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.460] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.461] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.462] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.463] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.464] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.465] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.466] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.467] [WARN  ] Q7K: Not enough space to send out frame (0 available, 84 needed)
[  249.468] [NOTICE] Q7K: =========================================
[  249.469] [NOTICE] Q7K:   CPU ON RECEIVED
[  249.469] [NOTICE] Q7K: =========================================
[  249.470] [NOTICE] Q7KCOM:  ======================================= 
[  249.471] [NOTICE] Q7KCOM:    BOOT FROM HOST READY 
[  249.472] [NOTICE] Q7K: QCA7K_SPI_REG_SIGNATURE = 0xAA55
[  249.473] [NOTICE] Q7K: =========================================
[  249.474] [NOTICE] Q7K:   QCA700x is READY
[  249.474] [NOTICE] Q7K: =========================================
[  251.490] [NOTICE] APL-ETH: Lost link:
[  251.491] [NOTICE] APL-ETH:     Interface: eth0
[  251.491] [NOTICE] APL-ETH:     MAC:       C4:93:00:21:56:65
[  251.492] [NOTICE] APL-MAIN: 
[  251.492] [NOTICE] APL-MAIN: =============================
[  251.493] [NOTICE] APL-MAIN: LAN CONFIGURATION DELETED: 
[  251.494] [NOTICE] APL-MAIN: for IP Config handle [fe00] 
[  251.494] [NOTICE] APL-MAIN: IPv6 Addresses:
[  251.495] [NOTICE] APL-MAIN:   Link-Local:  0:0:0:0 : 0:0:0:0
[  251.496] [NOTICE] APL-MAIN:   Local: 0:0:0:0 : 0:0:0:0
[  251.497] [NOTICE] APL-MAIN:   DNS1:  0:0:0:0 : 0:0:0:0
[  251.497] [NOTICE] APL-MAIN:   DNS2:  0:0:0:0 : 0:0:0:0
[  251.498] [NOTICE] APL-MAIN: =============================
[  251.499] [NOTICE] APL-MAIN: 
---------------------------------------------------------------------------------------------------------------

Can you please help us to rectify and solve this issue.

**Comment by Shekhar-devise** [comment]
I am sending the wire shark logs with code output.please check.
I have already set mirror state as per the white beet manual.
Getting same response again.

Initiating framing interface
iface: eth0, mac: C4:93:00:21:56:64
Ev configuration: {'mac': 'C4:93:00:21:56:64', 'ev': {'evid': 'C4:93:00:21:56:64', 'protocol_count': 2, 'protocols': [0, 1], 'payment_method_count': 1, 'payment_method': [0], 'energy_transfer_mode_count': 2, 'energy_transfer_mode': [0, 4]}, 'battery': {'timestep': 10000, 'capacity': 50000, 'level': 49000, 'full_soc': 100, 'bulk_soc': 80, 'max_current': 100, 'max_power': 12000, 'max_voltage': 300, 'target_current': 40, 'target_voltage': 200, 'target_voltage_delta': 10, 'max_current_AC': 0, 'max_voltage_AC': 0, 'min_current_AC': 0}}
Set the CP mode to EV
Start the CP service
Set SLAC to EV mode
Start SLAC
Wait until an EVSE connects
cp_dc = 5.5
EVSE connected
Start SLAC matching
SLAC matching successful
Set V2G mode to EV
Set V2G configuration
get v2g configuration
get conf res = {'evid': b'\x01\x02\x03\x04\x05\x06', 'protocol_count': 2, 'protocol': [0, 1], 'payment_method_count': 1, 'payment_method': [0], 'energy_transfer_mode_count': 1, 'energy_transfer_mode': [1], 'battery_capacity': 50000}
Set DC charging parameters
Set AC charging parameters
Start V2G
Change State to State C
controlPilotSetResistorValue res = 0
Create new charging session
ControlPilot duty cycle: 100.0

[wireshark_logs.pcapng.zip](https://github.com/Sevenstax/FreeV2G/files/8053026/wireshark_logs.pcapng.zip)

**Comment by Shekhar-devise** [comment]
@jpo-stx Hi have you found anything strange?

**Comment by jpo-stx** [comment]
Hi @Shekhar-devise it seems that the QCA is restarted and therefore looses the link:
[ 247.356] [NOTICE] Q7K: CPU ON RECEIVED
My collegue is currently checking why the QCA is restarted.
Have you started a v2g session before the one that is shown in the log?

**Comment by Shekhar-devise** [comment]
Have you found why QCA is restarting?
Have you started a v2g session before the one that is shown in the log?
yes, we have started the V2G session before the log.

**Comment by jpo-stx** [comment]
Hello @Shekhar-devise ,

we were not yet able to reproduce the issue. Further Questions:

- Which firmware version are you using?
- How often does it happen?
- Is it also happening in the first session after a reboot, or only in the following sessions?

**Comment by Shekhar-devise** [comment]
HI,
We are using the following firmware:
WHITEBEET_ISO15118_EV_V01_00_04.fwu

It happens every time when we are running it.

Yes it is also happening in the first senssion after a reboot.

**Comment by jpo-stx** [comment]
Can you please send me a complete log of the UART and wiresshark trace from boot on?

**Comment by Shekhar-devise** [comment]
Sharing a screenshot of the Firmware version that we are using
![Current_Firmware (1)](https://user-images.githubusercontent.com/99326580/163705593-e2e9e7a8-aaa0-4a25-9fa0-c285bc7ff28b.jpeg)
g

**Comment by jpo-stx** [comment]
Hi @Shekhar-devise ,

in the second line I see that you are using the old v1 of the QCA firmware. Can you try with the new version, by setting the DIP switch SW1 to "FW VER **NEW**".

Have you switched to the old version intentionally?

**Comment by Shekhar-devise** [comment]
We have changed that switch to "FW VER NEW" but the problem is the same.

**Comment by jpo-stx** [comment]
Do you have the possibility to use another counterpart on EVSE side?

Since we cannot reproduce this issue here can please do what I asked for in https://github.com/Sevenstax/FreeV2G/issues/38#issuecomment-1085591446:

> Can you please send me a complete log of the UART and wiresshark trace from boot on?

**Comment by Shekhar-devise** [comment]
@jpo-stx please check I have added the the whitebeet log from boot and EVSE simulator log.pleaes check
[EVSElog.txt](https://github.com/Sevenstax/FreeV2G/files/8541561/EVSElog.txt)
[PEV.txt](https://github.com/Sevenstax/FreeV2G/files/8541564/PEV.txt)
.

**Comment by jpo-stx** [comment]
@Shekhar-devise can you also add the wireshark log with port mirror enabled. It is importent to have both logs of the same process. So please start logging of the debug port and the ethernet with port mirror enabled an do a clean start of the Whitebeet module and attach the files to this issue. This would be really helpful to analyze the issue.

**Comment by lho-stx** [comment]
@Shekhar-devise,
as there is no progress in this issue it will be closed. If you still encounter this issue, please reopen!
Best regards,
lho
