### ISSUE TITLE
[SPI Interface] EVSE stuck in Request Charge Loop Parameters 

### ISSUE THREAD

**Issue by Joenoodoe** [Sevenstax/FreeV2G#43]
Hi All,

We're connecting module-EI and module-PI with SPI interface.
Currently, we have some problem in module-EI when sending **Request Charge Loop Parameters**  command.

1. But the data response from the module-EI is "55 55 00 00 C0 27 70 37 00 01 **05** A8 C1".
    **05** -> Unexpected message; module is not in a state to execute the command
    and the message log comes with
    **[NOTICE] V2GISO13: Message performance timeout of 75ms reached.**
    
2. We knew that it's the problem about the timeout.
    We check for the TX_PENDING pin it shows that we didn't fetch any data when TX PENDING goes high.
    It cause we can't fetch the data in real time. What would be the problem ?
 
![la](https://user-images.githubusercontent.com/86946265/157856387-17b558c8-8a43-4d79-86ad-bf0e169308b0.png)

BR.
Joechen

**Comment by jpo-stx** [comment]
Hi @Joenoodoe ,

do you receive the request charge loop parameters status message after this "zero" message?

Can you add some time axis to the graph, or tell me what the time between the chip select activation and the first clock is. There are some timeing requirements, which are described in chapter 9.2.6 Timings in the manual.
