### ISSUE TITLE
PEV - Missing Notification (stop Charging or Renegotiation)

### ISSUE THREAD

**Issue by PawelBiela3** [Sevenstax/FreeV2G#44]
Hello,

In during implementation of post charging phase, I found, that WhiteBeet(EV) doesn't send notfication(0xCC) to host.
Could You check, what can be reason?

**Traces from WhiteBeet:**
APPLICATION:
  Name:      ISO15118 (EV)
  Version:   V01_00_04
  Target:    WHITE-BEET
  CPU:       STM32F745
 
PRODUCT VERSION:
 String: SEVENSTAX_LIB_V_10_02_01
 Hex:    0x000a0201
 Dec:    100201
 
 Hostcontroller Interface: SPI!
 
APPLICATION RUNNING ...
[    0.005] [NOTICE] APL-MAIN: BOOT-CFG: Boot QCA7005 firmware from host
[    0.005] [NOTICE] APL-MAIN: BOOT-CFG: FW2
[    0.006] [NOTICE] APL-MAIN: BOOT-CFG: Module configured to EV
[    0.008] [NOTICE] Q7KCOM:  Boot from host selected
[    0.011] [NOTICE] SLAC: stxSLAC_Init()
[    0.013] [NOTICE] APL-ETH:   MAC of NIC[0]:	c4:93:00:21:55:de
[    5.291] [NOTICE] APL-ETH:   MAC of NIC[1]:	c4:93:00:21:55:dd
[    5.297] [NOTICE] V2GCPS: stxV2GCPS_RegisterCallback()
[    5.510] [NOTICE] Q7K: QCA7K_SPI_REG_SIGNATURE = 0xAA55
[    5.511] [NOTICE] Q7K: =========================================
[    5.511] [NOTICE] Q7K:   QCA700x is READY
[    5.512] [NOTICE] Q7K: =========================================
[    5.513] [NOTICE] Q7KCOM: Reset QCA700x
[    5.515] [NOTICE] Q7K: =========================================
[    5.515] [NOTICE] Q7K:   CPU ON RECEIVED
[    5.516] [NOTICE] Q7K: =========================================
[    5.517] [NOTICE] Q7K: QCA7K_SPI_REG_SIGNATURE = 0xAA55
[    5.518] [NOTICE] Q7K: =========================================
[    5.519] [NOTICE] Q7K:   QCA700x is READY
[    5.519] [NOTICE] Q7K: =========================================
[    6.385] [NOTICE] Q7KCOM:  ======================================= 
[    6.386] [NOTICE] Q7KCOM:    FW and PIB was loaded successful 
[    6.901] [NOTICE] Q7K: =========================================
[    6.901] [NOTICE] Q7K:   CPU ON RECEIVED
[    6.902] [NOTICE] Q7K: =========================================
[    6.903] [NOTICE] Q7KCOM:  ======================================= 
[    6.903] [NOTICE] Q7KCOM:    BOOT FROM HOST READY 
[    6.905] [NOTICE] Q7K: QCA7K_SPI_REG_SIGNATURE = 0xAA55
[    6.905] [NOTICE] Q7K: =========================================
[    6.906] [NOTICE] Q7K:   QCA700x is READY
[    6.907] [NOTICE] Q7K: =========================================
[    7.071] [NOTICE] Q7KCOM:  Own QCA7K MAC = C4:93:00:21:55:DF
[    8.527] [NOTICE] SLAC: stxSLAC_Start()
[   21.013] [NOTICE] V2GCPS: Changed Max Current EV State (1)
[   21.013] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[   21.014] [NOTICE] V2GCPS: stxXBAR_V2GCPS_NotifyHandler()
[   21.015] [NOTICE] V2GCPS: # V2GCPS_INFOTYPE_CP_DUTY_CYCLE
[   21.015] [NOTICE] V2GCPS: Duty cycle is 56 permill
[   21.081] [NOTICE] SLAC: stxSLAC_StartSlacMatchingProcess()
[   21.274] [WARN  ] SLAC: # SLAC_STATE_RECV_SLAC_PARAM_CNF - TIMEOUT
[   24.481] [NOTICE] Q7KCOM: PIB File was updated => Download PIB without reset
[   27.230] [NOTICE] Q7KCOM: PIB File was updated => Download PIB without reset
[   27.409] [NOTICE] APL-ETH: Got link:
[   27.410] [NOTICE] APL-ETH:     Interface: eth0
[   27.410] [NOTICE] APL-ETH:     MAC:       C4:93:00:21:55:DE
[   27.411] [NOTICE] SLACSERV: # NC_SLAC_SUCCESS
[   27.717] [NOTICE] V2GSVC: Starting in EV mode.
[   29.119] [NOTICE] APL-MAIN: 
[   29.119] [NOTICE] APL-MAIN: =============================
[   29.120] [NOTICE] APL-MAIN: NEW LAN CONFIGURATION (IPv6): 
[   29.120] [NOTICE] APL-MAIN: for IP Config handle [fe00] 
[   29.121] [NOTICE] APL-MAIN: IPv6 Addresses:
[   29.122] [NOTICE] APL-MAIN:   Link-Local:  fe80:0:0:0 : c693:ff:fe21:55de
[   29.123] [NOTICE] APL-MAIN:   Local:	0:0:0:0 : 0:0:0:0
[   29.123] [NOTICE] APL-MAIN:   DNS1:	2001:4860:4860:0 : 0:0:0:8888
[   29.124] [NOTICE] APL-MAIN:   DNS2:	fd00:0:0:0 : be05:43ff:fe44:5280
[   29.125] [NOTICE] APL-MAIN: =============================
[   29.126] [NOTICE] APL-MAIN: 
[   29.377] [WARN  ] V2GSVC: Security options satisfied, connect!
[   29.383] [NOTICE] V2GSVC: TCP: Connected to server without TLS
[   31.311] [NOTICE] V2GAPP: Received event 'Session started'
[   31.883] [NOTICE] V2GAPP: Received event 'Schedule received'
[   31.884] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   31.885] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   31.886] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   31.887] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   31.888] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   31.889] [NOTICE] V2GAPP: Received event 'Ready for cable check'
[   32.340] [NOTICE] V2GAPP: Received event 'Cable check finished'
[   32.340] [NOTICE] V2GAPP: Received event 'Ready for pre charging'
[   32.746] [NOTICE] V2GAPP: Received event 'Ready for charging'
[   33.151] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   33.152] [NOTICE] V2GAPP: Received event 'Ready for charging'
[   33.556] [NOTICE] V2GAPP: Received event 'Charging started'
[   33.711] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   33.712] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   33.713] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   33.714] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   33.866] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.021] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.176] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.331] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.486] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.641] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.797] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   34.951] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   35.106] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   35.262] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   35.418] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   35.572] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   35.726] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   35.881] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.037] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.193] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.348] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.503] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.659] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.814] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   36.969] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   37.124] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   37.127] [WARN  ] APL-ETH: # Unhandled Ethernet notifycode 365
[   37.279] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   37.435] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   37.591] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   37.746] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   37.901] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   38.056] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'
[   38.211] [NOTICE] V2GAPP: Received event 'DC charge parameters changed'

**PLC sniffs**
![renegotiation](https://user-images.githubusercontent.com/97530856/158201973-f98e1e7d-6af1-4bcf-998c-cb9bfc5bd064.png)

**Comment by jpo-stx** [comment]
Hi @PawelBiela3 , please update to the new V01_00_05 firmware.

A notification should be received when the EVSE requests stop charging or renegotiation.
