### ISSUE TITLE
[Query] Could the module upgrade and downgrade ?

### ISSUE THREAD

**Issue by Joenoodoe** [Sevenstax/FreeV2G#50]
Hi,

Currently, I want to test the newest version(V.02_00_00) in module-EI. 

Because there's only one module-EI board to test, I want to make sure whether the module-EI could be upgrade and downgrade if I want ?

Thanks.
BR
JoeChen

**Comment by jpo-stx** [comment]
Hi @Joenoodoe ,

yes, you can upgrade to V02_00_00 and then downgrade back to older versions. (i.e. V01_01_07)

**Comment by ColinCGC** [comment]
I'm not so sure about that - I upgraded an EI to V02_00_00 (in a futile effort to get the reference app actually working), and now it refuses to downgrade.

```
18.819] APL: [ 0] FWU X -> 0 %
[   18.925] APL: [ 1] FWU X -> 0 %
[   18.928] APL: FWU STATUS: ERROR
[   18.937] APL: [ 2] FWU (NOT STARTED)
[   18.950] APL: [ 3] FWU (NOT STARTED)
```

```
Welcome the SEVENSTAX SFWU Updater

Initiating framing interface
Starting update process
Firmware update at 0 percent; Sent: 833 Bytes
[!] Error: Device rejected update file
```

**Comment by jpo-stx** [comment]
Hi @ColinCGC the V02_00_00 checks the validity of the certificate before verfiying the signature of the firmware. Have you set the time on the Whitebeet? See user manual "12.3.1 Set Time"

**Comment by ColinCGC** [comment]
No, I have not set the time, that should do the trick if it's checking the certificate. I won't try it now (as V02_00_00 is working ok), but will bear in mind for future updates, thank you.

**Comment by Sertplas** [comment]
I can confirm that after setting the time, i successfully downgraded the module from v2 to v1.0.7. But i think it would be beter if software updater should do this by himself before starting the update procedure
