### ISSUE TITLE
[Query] When will release the Plug and Charge firmware in module-PI ?

### ISSUE THREAD

**Issue by Joenoodoe** [Sevenstax/FreeV2G#51]
Hi,

We want to test module-PI for plug and charge and connect to module-EI (V 02_00_00  PnC version).

Has the official version for PnC of module-PI been released yet ? If not yet, do you know when firmware will be available?

Thanks for the supports.

BR 
JoeChen

**Comment by Joenoodoe** [comment]
Hi,

Any updates for this query ?

Thanks.
JoeChen

**Comment by ttu-stx** [comment]
PEV side White Beet FW with PnC functionality is planned for later this year.
A more precised date will be announced in the discussions area as soon as it is available.
