### ISSUE TITLE
Test mode for power spectral density calibration?

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#52]
Is there a software "test mode" that ensures the following behavior? 

- QCA7000/QCA7005 is accessible over CP
- Fixed and known NMK (i.e. randomization disabled)
- PWM generation on CP disabled (+12VDC is ok)

Such a mode would enable PSD calibration which is important for tuning SLAC attenuation parameters. Thanks for your time.

**Comment by vbudko** [comment]
Hi Zach,
You can send a request set NMK in the WHITE-beet module, e.g. with plctool -M command, which would just set default HomePlug AV NMK using VS_SET_KEY.REQ.
When you do not initialize CP service, CP voltage would be -12V DC, if you do initialize, then it will turn to +12V DC.
BR, Vasily

> Is there a software "test mode" that ensures the following behavior?
> * QCA7000/QCA7005 is accessible over CP
> * Fixed and known NMK (i.e. randomization disabled)
> * PWM generation on CP disabled (+12VDC is ok)
> Such a mode would enable PSD calibration which is important for tuning SLAC attenuation parameters. Thanks for your time.

**Comment by zacharyalutz** [comment]
Thanks for the super fast response :)
