### ISSUE TITLE
WHITEbeet-EI Port mirror

### ISSUE THREAD

**Issue by fmodi-sls** [Sevenstax/FreeV2G#53]
Hello,

We are planning to connect Whitebeet E1 with host controller via SPI interface. Can we enable port mirror on eth interface?
Both SPI and Eth interface will work togather? SPI as normal communication interface with host and ETH as port mirror with GreenShark when ever needed?

**Comment by jpo-stx** [comment]
Hi @fmodi-sls ,
I just tested this setup and it work just fine!
