### ISSUE TITLE
WB V02_00_01 problem

### ISSUE THREAD

**Issue by codderembedded** [Sevenstax/FreeV2G#59]
we installed to WB V02_00_01. And we connected to the debug port:

[   16.495] [NOTICE] APL-MAIN: 
[   18.698] [NOTICE] APL-ETH: Got link:
[   18.698] [NOTICE] APL-ETH:     Interface: eth1
[   18.699] [NOTICE] APL-ETH:     MAC:       C4:93:00:21:50:91
[   20.223] [NOTICE] APL-MAIN: 
[   20.223] [NOTICE] APL-MAIN: =============================
[   20.224] [NOTICE] APL-MAIN: NEW LAN CONFIGURATION (IPv6): 
[   20.224] [NOTICE] APL-MAIN: for IP Config handle [fe01] 
[   20.225] [NOTICE] APL-MAIN: IPv6 Addresses:
[   20.226] [NOTICE] APL-MAIN:   Link-Local:  fe80:0:0:0 : c693:ff:fe21:5091
[   20.227] [NOTICE] APL-MAIN:   Local:	0:0:0:0 : 0:0:0:0
[   20.227] [NOTICE] APL-MAIN:   DNS1:	2001:4860:4860:0 : 0:0:0:8888
[   20.228] [NOTICE] APL-MAIN:   DNS2:	fd00:0:0:0 : be05:43ff:fe44:5280
[   20.229] [NOTICE] APL-MAIN: =============================
[   20.230] [NOTICE] APL-MAIN: 
[   22.251] [WARN  ] APL-ETH: # Unhandled Ethernet notifycode 365
[   30.252] [WARN  ] APL-ETH: # Unhandled Ethernet notifycode 365

Why Unhandled Ethernet notifycode 365. How we can fix it?

**Comment by jpo-stx** [comment]
Hi @codderembedded ,

this doesn't need to be fixed. We will remove this warning in one of the next versions.
