### ISSUE TITLE
Updating to V02.00.01

### ISSUE THREAD

**Issue by lherreraalloza** [Sevenstax/FreeV2G#60]
Hi,

Following suggestions on https://github.com/Sevenstax/FreeV2G/issues/40, I have updated the WB EVSE to the last available firmware release available in https://downloads.codico.com/misc/plc/index.php (V02.00.01) in order to solve timeout issues during the charge loop.

Firmware update was finished successfully, but after installing V02.00.01 I cannot communicate with the EVSE. Neither by ethernet nor by the console port. How can I perform a downgrade?

Firmware update to V02.00.01
![image](https://user-images.githubusercontent.com/3297410/165743121-c288b2ec-0bde-4ef6-a997-723edc33061c.png)

Firmware downgrade to V01.01.07
![image](https://user-images.githubusercontent.com/3297410/165743167-f63b532b-97f0-4c34-9073-acae71a251e0.png)

**Comment by lherreraalloza** [comment]
Correction: Console port is working. The issue is only in the ethernet port (duplicated issue with https://github.com/Sevenstax/FreeV2G/issues/59).

**Comment by jpo-stx** [comment]
V02_00_00 checks the validity of the certificate before verfiying the signature of the firmware. The time needs to be set on the Whitebeet? See user manual "12.3.1 Set Time"
