### ISSUE TITLE
WB V02_00_XX firmware upgrade/downgrade problem

### ISSUE THREAD

**Issue by IonelFratila** [Sevenstax/FreeV2G#63]
Hi @jpo-stx ,
I had to reopen the issue #56 because I think there is a problem with the new firmware update tool, StxFwUpdater.exe ver.2.4, when running in Win10 (I did not test under Linux). I tried to downgrade the firmware to V.01.01.06 and then back upgrade to V.02.00.01. The upgrade is executed normally but StxFWUpdater.exe does not properly finishes the upgrade (it displays continuously the update message, as you can see in the attached log) and I had no solution than Ctrl^C to stop execution. After changing firmware, WB seems to be OK (it reports the new FW version). Please confirm if the upgrade is OK and I can use the WB module, even in these conditions.
Thank You,
Ionel Fratila

C:\Users\admin\Desktop\WB_Update\Windows>StxFwUpdater -f WHITEBEET_ISO15118_EVSE_V02_00_01.fwu -t C4:93:00:21:50:B5 -i "Ethernet"
Welcome to the SEVENSTAX SFWU Updater 2.4

Initiating framing interface
Starting update process
Firmware update at 0 percent; Sent: 833 Bytes
Firmware update at 4 percent; Sent: 70805 Bytes
Firmware update at 15 percent; Sent: 82467 Bytes
Firmware update at 28 percent; Sent: 151606 Bytes
Firmware update at 43 percent; Sent: 232407 Bytes
Firmware update at 59 percent; Sent: 313208 Bytes
Firmware update at 74 percent; Sent: 394009 Bytes
Firmware update at 90 percent; Sent: 474810 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 100 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Firmware update at 0 percent; Sent: 523571 Bytes
Traceback (most recent call last):
  File "FirmwareUpdateEthernetFrames.py", line 326, in <module>
  File "FirmwareUpdateEthernetFrames.py", line 141, in perform_firmware_update
KeyboardInterrupt
[11960] Failed to execute script 'FirmwareUpdateEthernetFrames' due to unhandled exception!

**Comment by jpo-stx** [comment]
Hi @IonelFratila ,
this seems to be an issue with the tool, if the Whitebeet has received all the data it will send a status message and reboot to update the firmware,
It seems that the tool is missing this status message,

**Comment by jpo-stx** [comment]
@IonelFratila , there should be a new version 2.5 of the tool available, which resolves this issue.
