### ISSUE TITLE
Set Port Mirror Configuration response code 0x12

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#73]
### Setup
Platform: EVSE
Firmware Version: V02_00_01
Host Controller Interface: Ethernet
Host: Own Implementation

### Description
Host receives non-zero response code after enabling/configuring port mirror thru _Network Configuration Service_. There is no definition for this response code in the documentation. It appears that the port mirroring function is not working.

### To Reproduce
1. Send _Set Port Mirror State_ to ON
  host: ```c0 05 55 09 00 01 01 18 c1```
  wb:   ```c0 05 55 09 00 01 00 19 c1```
2. Send _Set Port Mirror Configuration_ to sniff on _eth0_ and mirror to _eth1_ (notice wb response code is **0x12**)
host: ```c0 05 57 0a 00 0a 04 65 74 68 30 04 65 74 68 31 1f c1```
wb:   ```c0 05 57 0a 00 01 12 04 c1```

### Expected behavior
After issuing the _Set Port Mirror Configuration_ command to whitebeet, I would expect the response code to be 0x00. This same message sequence worked as expected for Whitebeet firmware v01_01_07.

### Logs
[port-mirror-fail.pcapng.gz](https://github.com/Sevenstax/FreeV2G/files/9057390/port-mirror-fail.pcapng.gz)

**Comment by jpo-stx** [comment]
Hi @zacharyalutz ,

the PLC interface which was named `eth0` before, is now named `plc0`. This wasn't changed in the documentation yet. The default configuration is mirror from powerline to ethernet, you can see this when you read out the configuration.

With the following frame you should achieve what you want:
`c0 05 57 0a 00 0a 04 70 6c 63 30 04 65 74 68 31 00 c1`
