### ISSUE TITLE
MG ZS Vehicle Test Problem

### ISSUE THREAD

**Issue by codderdreamer** [Sevenstax/FreeV2G#80]
We are testing different vehicles and the mg is having problems. Why does the car charge for a while and send a session stop? 
I am sending wireshark, terminal and whitebeet debug.
[mg.zip](https://github.com/Sevenstax/FreeV2G/files/9505637/mg.zip)

**Comment by jpo-stx** [comment]
Hello @codderdreamer ,
there is no PLC communication present in the wireshark log. Did you enable the port mirror and are you connected directly to the whitebeet?

**Comment by codderdreamer** [comment]
yes for example;
Port mirror is enable. I connected directly to the whitebeet
![Screenshot from 2022-09-26 15-02-54](https://user-images.githubusercontent.com/49305144/192271632-98306e0d-774b-4995-b944-2235dce090fa.png)
![Screenshot from 2022-09-26 15-03-53](https://user-images.githubusercontent.com/49305144/192271662-c18e2d2a-5a21-4f0a-abfa-04d8053cb724.png)

**Comment by jpo-stx** [comment]
If you are connected directly to the whitebeet (no switch in between) and the port mirror is on (which I can see in the logs) the high level communication on the TCP protocol should be seen in the log, which is not the case here.

**Comment by lho-stx** [comment]
This issue is closed due to inactivity. If the issue is still present, please re-open the issue!
