### ISSUE TITLE
Reference implementation in SPI?

### ISSUE THREAD

**Issue by kramzarales** [Sevenstax/FreeV2G#98]
I would be interested to know if there are any plans for a version of FreeV2G that use the SPI interface on the whitebeet instead of Ethernet?

If there isnt, would someone perhaps have any contacts or code that someone who has succesfully done this SPI modification , would be willing to share?

**Comment by jpo-stx** [comment]
Hi @kramzarales ,
we have an implementation for the Raspberry Pi, which is available in the plug and charge branch:
https://github.com/Sevenstax/FreeV2G/blob/plug_and_charge

Have a look at the SPI adapter:
https://github.com/Sevenstax/FreeV2G/blob/plug_and_charge/SpiAdapter.py

You can start the application with SPI interface like this:
```
python3 Application.py spi -i spidev0.0 -m c4:93:00:22:22:22 -r EVSE
```

**Comment by kramzarales** [comment]
Thank you so much for this.

Just a heads up. https://github.com/Sevenstax/FreeV2G/blob/plug_and_charge  doesnt appear to work.
